### ISSUE TITLE
Navigation from PHP class to its XML declaration

### ISSUE THREAD

**Issue by voleye** [magento/magento2-phpstorm-plugin#1]
### Overview
Currently the navigation from PHP class to its xml declaration support only for
 - di.xml
 - events.xml
 - layout xml files

but Magento also has other xml files contains PHP classes like: crontab.xml, extension_attributes.xml, product_options.xml, etc...

### Acceptance Criteria
 - It is possible to navigate from PHP class to its XML declaration regardless of xml file where PHP class was declared

**Comment by voleye** [comment]
Done, please, see PR #12

**Comment by paliarush** [comment]
The fix will be released in 0.3.0 version in the nearest days.
