### ISSUE TITLE
Constructor injection and routine automation

### ISSUE THREAD

**Issue by Stepa4man** [magento/magento2-phpstorm-plugin#100]
As a developer, I don't want to spend the time on all di related routines.

### As is:
1. Go to constructor
2. Add new dependency
3. Click Option+Return
4. Click "Initialize properties"
5. Choose the property and click return
6. Click Option+Return
7. Click Update PHPDoc block

### Has to be:
1. Go to constructor
2. Create a new line in the list of arguments
3. Click Option+Return (or any other way to achieve action)
4. Click inject dependency
5. Choose the class and optionally choose argument name

#### Result: 
- Dependency injected through the constructor
- Private property created
- Constructor's doc block updated

**Comment by VitaliyBoyko** [comment]
Hi @Stepa4man 

This is a great idea but I think it is related more to PHP in general than to Magento. Could you please consider submitting this to JetBrains https://blog.jetbrains.com/phpstorm/2019/06/phpstorm-and-youtrack-we-want-your-feedback/

Thank you!

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, is this ticket still up for grabs or can we close this in reference to your above comment?
