### ISSUE TITLE
Update controller related labels and fields in the Create a new Magento 2 UI Component Form

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1007]
**Is your feature request related to a problem? Please describe.**

Original issue was reported in the #598.

**Target dialog fields:**

<img width="1219" alt="Screenshot 2022-02-18 at 11 46 14" src="https://user-images.githubusercontent.com/31848341/154659735-38e87c61-890a-4628-9e6f-e77507269b8f.png">

**Describe the solution you'd like** (*)

We should change controller generation related field labels to the similar as in the #962.
Also we should add appropriate placeholders as in the #962.

Placeholders support was added in the #938.

**Describe alternatives you've considered**

N/A.

**Additional context**

Mainline branch: **4.3.0-develop**

**Comment by doninAtwix** [comment]
@magento I am working on this
