### ISSUE TITLE
Module files action group is accessible from the theme context

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1010]
**Describe the bug** (*) 

We can access the **Module files** action group from the theme context.

**To Reproduce** (*) 

1. Go to any custom theme in the app/design/
2. Click on the any folder in the theme or even outer of it
3. The New Magento 2 module action is available here
4. Create new module in the theme
5. All context actions are available here

**Expected behavior** (*) 

- There is no possibility to create a new Magento 2 module outer of the app/code directory.
- There is no possibility to see any context actions in the module inside a theme (because such modules should not be there)

**Screenshots**

<img width="885" alt="Screenshot 2022-02-18 at 16 56 27" src="https://user-images.githubusercontent.com/31848341/154706630-442f6f87-eff5-4fd4-904a-f2a56d01ec5f.png">
<img width="885" alt="Screenshot 2022-02-18 at 16 58 18" src="https://user-images.githubusercontent.com/31848341/154706981-92225ab7-ef67-41b9-8dc5-91c2520c9371.png">

**Please complete the following information:** (*) 

 - OS: Any
 - PhpStorm/Intellij version: Any
 - Plugin Version: Any

**Additional context**

@Iamwade, thank you for reporting this issue.

**Comment by Iamwade** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
Hi @bohdan-harniuk .
The code for displaying the menu Module file and groups of xml files was compared. The logic of checking the context menu called in the module and checking the visibility was borrowed. It was not possible to restrict the display for subfolders in the module.

Thanks

**Comment by bohdan-harniuk** [comment]
The first expected behaviour condition (there is no possibility to create a new Magento 2 module outer of the app/code directory.) has been already fixed in the #633
