### ISSUE TITLE
Code Generator uses prohibited code snippets

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#1011]
**Describe the bug** (*) 

When I created the Grid using the plugin, there is a code fragment in the class `\Vendor\Module\Ui\Component\Listing\Column\EntityBlockActions`

```
    /**
     * Url paths.
     * #@+
     */
    private const EDIT_URL_PATH = 'module/entity/edit';
    private const DELETE_URL_PATH = 'module/entity/delete';
    /**  */
```

but `#@+` and `#@-` fragments should not be present in the code. You can check [here](https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#docblock-templates).

`@inheritdoc` is also found in this class and in many other places, but at the moment this tag is used incorrectly in Magento in many places, and when new such tags are contributed, this code does not pass the review code.

The `@inheritdoc` tag SHOULD NOT be used. You can check [here](https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#inheritdoc).

```
    /**
     * @inheritDoc
     */
    public function prepareDataSource(array $dataSource): array
    {
```

**To Reproduce** (*) 

1. Create UI Grid through context menu
2. Check `\Vendor\Module\Ui\Component\Listing\Column\EntityBlockActions`
4. See generated content

**Expected behavior** (*) 

Code without using forbidden fragments

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/154926700-ea47f754-b528-4a7e-b602-d2e86ec417cc.png)

**Please complete the following information:** (*) 
![image](https://user-images.githubusercontent.com/1055999/154926767-edd055fa-7364-4b2b-b300-736679a1e938.png)

 - OS: MacOS
 - PhpStorm/Intellij version: [e.g. 2021.3.2]
 - Plugin Version: 4.2.3

**Additional context**

- [@inheritDoc](https://github.com/magento/magento2-phpstorm-plugin/search?q=inheritDoc&type=code) search results
- [#@+](https://github.com/magento/magento2-phpstorm-plugin/search?l=PHP&q=%23%40%2B&type=code) search results

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs!

Thank you for your suggestions!
We'll try to review all existing code generators to eliminate such prohibited annotations.

Regards,

**Comment by doninAtwix** [comment]
@magento I am working on this
