### ISSUE TITLE
[UCT] Cover themes scanning/reporting for the Tools > Run The Upgrade Compatibility Tool

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1023]
For now only real-time UCT inspections are available for the themes in the Magento 2. 

We should add themes support of the UCT action execution.

**Describe the solution you'd like** (*)

⚠️ Scan themes after all modules. 
Add the same heading as for the module for each module inside a theme:

<img width="1140" alt="Screenshot 2022-03-04 at 11 09 53" src="https://user-images.githubusercontent.com/31848341/156734058-3f3295b1-3256-4a1e-8d53-ecfceaaea018.png">

Above add a heading with the theme name, as for an ex.: 
```bash
Theme Name: frontend/Testgento/store
--------------------
```

Maybe we should add separate setting to specify path to the theme folder:

<img width="605" alt="Screenshot 2022-03-04 at 11 20 19" src="https://user-images.githubusercontent.com/31848341/156735662-ff6de12e-aa8c-4de8-93e9-50ea18619dde.png">

⚠️ Update summary information to include number of scanned modules in the themes, number of scanned themes.
⚠️ Scanned themes must be included in the upgrade complexity scores. 

**Describe alternatives you've considered**

N/A. But any ideas will be appreciated.

**Additional context**

Module locator: `com.magento.idea.magento2uct.util.module.UctModuleLocatorUtil`
Output util: `com.magento.idea.magento2uct.execution.output.UctReportOutputUtil`
Report builder: `com.magento.idea.magento2uct.execution.output.ReportBuilder`

Mainline branch: **mainline/uct-1023-theme-scanning-feature**

**Comment by doninAtwix** [comment]
@magento I am working on this
