### ISSUE TITLE
MFTF: ActionGroup name autocomplete and reference

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-phpstorm-plugin#103]
### Preconditions (*)
![MFTF PHPStorm plugin (1)](https://user-images.githubusercontent.com/1639941/78461907-36eb8780-76cd-11ea-85dc-59b2647220a1.png)

#### Resources
Where are the source files located (that need to be indexed)

1. Action Group definitions (1 per file) `ActionGroup/*ActionGroup.xml` and ActionGroup/*/*ActionGroup.xml (<actionGroup name="..."[ extends="..."]> node) (Example: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/Test/Mftf/ActionGroup/AdminLoginActionGroup.xml)

#### Uses
Where the previously defined Action Groups are going to be used

1. In all `Test/*Test.xml` and `Test/*/*Test.xml` files. The tag is`<actionGroup ref="...">` which refers to previously indexed `<actionGroup name="...">`
1. In all Action Groups `<actionGroup extends="...">` refers to `<actionGroup name="...">` Example: https://github.com/magento/magento2/blob/70cf0c233728baaa6e1dff6a60b91062c911fe25/app/code/Magento/Captcha/Test/Mftf/ActionGroup/AdminLoginWithCaptchaActionGroup.xml#L11

### Steps to reproduce (*)
1. Start typing
    a) `<actionGroup extends="` in Action Group XML file
    b) `<actionGroup ref="` in Test XML file

### Expected result (*)
1. Have suggestions for the Action Groups indexed in the project.

### Actual result (*)
N/A

**Comment by VitaliyBoyko** [comment]
ℹ️ <actionGroup extends=" in Action Group XML file
Already done:
![image](https://user-images.githubusercontent.com/20116393/78504246-79b46a80-7774-11ea-9410-041992af858d.png)
ℹ️ <actionGroup ref=" in Test XML file
Done as well.
![image](https://user-images.githubusercontent.com/20116393/78504273-ac5e6300-7774-11ea-85ee-a31e2f4dbb3f.png)

@lbajsarowicz 
Please check the functionality in the latest develop branch. In case if the functionality does not satisfies acceptance criteria fill free to reopen the issue. Thank you!
