### ISSUE TITLE
Eliminate deprecated FilenameIndex#getVirtualFilesByName method usage

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1031]
**Is your feature request related to a problem? Please describe.**

The `com.intellij.psi.search.FilenameIndex#getVirtualFilesByName(com.intellij.openapi.project.Project, java.lang.String, com.intellij.psi.search.GlobalSearchScope)` method is deprecated. It is used in the: `com.magento.idea.magento2plugin.reference.provider.FilePathReferenceProvider#getReferencesByElement`.

**Describe the solution you'd like** (*)

1. Eliminate usage of deprecated method.
2. Do code refactoring of the file (just semantic refactoring, do not break the logic)

Mainline branch: **4.3.0-develop**

**Comment by doninAtwix** [comment]
@magento I am working on this
