### ISSUE TITLE
Eliminate deprecated Function#getReturnType method usage

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1035]
**Is your feature request related to a problem? Please describe.**

The `com.jetbrains.php.lang.psi.elements.Function#getReturnType` method is deprecated. It is used in the: `com.magento.idea.magento2plugin.actions.generation.util.FillTextBufferWithPluginMethods#execute`.

**Describe the solution you'd like** (*)

1. Eliminate usage of deprecated method

Mainline branch: **4.3.0-develop**

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
https://github.com/magento I am working on this

**Comment by doninAtwix** [comment]
@magento I am working on this
