### ISSUE TITLE
MFTF: Entity name autocomplete and reference

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-phpstorm-plugin#104]
### Preconditions (*)
![MFTF PHPStorm plugin (2)](https://user-images.githubusercontent.com/1639941/78462027-98602600-76ce-11ea-93cb-76125b5aa081.png)

#### Resources
Where are the source files located (that need to be indexed)

1. Entity definitions (multiple per file) Data/*Data.xml (<entity name="..."> nodes) (Example: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/Test/Mftf/Data/CookieConfigData.xml)

#### Uses (In Test and Action Group)
Where the previously defined Entities are going to be used

1. `<createData entity="...">` and `<updateData entity="...">` refers to `<entity name="...">` defined https://github.com/magento/magento2/blob/70cf0c233728baaa6e1dff6a60b91062c911fe25/app/code/Magento/Backend/Test/Mftf/Test/AdminDashboardWithChartsChart.xml#L24-L26
1. `<* userInput="{{entity.field}}"` where entity refers either to `<createData stepKey="...">` or `<entity name="...">`, field refers to `<data name="...">` abovem entioned. https://github.com/magento/magento2/blob/236988709f6db007988ca274bfbf837c2b609bb0/app/code/Magento/Bundle/Test/Mftf/ActionGroup/ViewBundleProductInAdminGridActionGroup.xml

#### Uses (In Entities)

1. `<entity extends="...">`

### Steps to reproduce (*)

1. Start typing
    a) `<createData entity="` in Action Group or Test
    b) `<updateData entity="` in Action Group or Test
    c) `<* userInput="{{` in Action Group or Test
    d) `<entity extends="` in Data (Entity)

### Expected result (*)
1. Autocomplete hints the entities defined in the project.

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by VitaliyBoyko** [comment]
Hi @lbajsarowicz 
All the mentioned functionality already implemented.
ℹ️  <createData entity=" in Action Group or Test
![image](https://user-images.githubusercontent.com/20116393/78504993-0a8d4500-7779-11ea-8b80-4390ae36a0f9.png)

ℹ️ <updateData entity=" in Action Group or Test
![image](https://user-images.githubusercontent.com/20116393/78505000-1547da00-7779-11ea-8d0b-069805dbe760.png)

ℹ️) <* userInput="{{ in Action Group or Test
![image](https://user-images.githubusercontent.com/20116393/78505006-1f69d880-7779-11ea-92bf-e2b8603d2f8f.png)

ℹ️ <entity extends=" in Data (Entity)
![image](https://user-images.githubusercontent.com/20116393/78505012-255fb980-7779-11ea-9d33-f45a392e997b.png)

Please check the functionality in the latest develop branch. In case if the functionality does not satisfies acceptance criteria fill free to reopen the issue. Thank you!

**Comment by lbajsarowicz** [comment]
It does not work properly: 
![image](https://user-images.githubusercontent.com/1639941/78505231-5c7e9c80-7772-11ea-8c58-a169ed820d37.png)

It suggests Sections not entities :-(

**Comment by VitaliyBoyko** [comment]
@lbajsarowicz 
Thank you for the clarification.
