### ISSUE TITLE
MFTF: Page (URL) reference and autocomplete

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-phpstorm-plugin#105]
### Preconditions (*)
![MFTF PHPStorm plugin (3)](https://user-images.githubusercontent.com/1639941/78462166-d6117e80-76cf-11ea-81c6-51cb880dc08a.png)

#### Resources
Where are the source files located (that need to be indexed)

1. Page definitions (1 per file) `Page/*Page.xml` (`<page name="..." url="...">` node) (Example: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/Test/Mftf/Page/AdminLoginPage.xml)

#### Uses (in Test and Action Group)
Where the previously defined Pages are going to be used

1. `<* url="{{$PAGE.url}}">` refers to `<page name="..." url="...">` where $PAGE means name="..." value.

### Steps to reproduce (*)
1. Start typing `... url="{{` in Test or ActionGroup XML node

### Expected result (*)
1. Autocomplete suggests indexed Pages.

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by VitaliyBoyko** [comment]
Hi, @lbajsarowicz 
ℹ️ This is already implemented.
![image](https://user-images.githubusercontent.com/20116393/78505182-63a9a880-777a-11ea-863e-f93877db7502.png)

Please check the functionality in the latest develop branch. In case if the functionality does not satisfies acceptance criteria fill free to reopen the issue. Thank you!

**Comment by lbajsarowicz** [comment]
It's not suggesting Pages but Sections :-(
![image](https://user-images.githubusercontent.com/1639941/78505248-82a43c80-7772-11ea-8edb-8dc83b5f472f.png)
