### ISSUE TITLE
Add raw plugin verifier configuration

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1050]
**Is your feature request related to a problem? Please describe.**

It would be great to have a raw configuration for the plugin verifier tool: https://plugins.jetbrains.com/docs/intellij/api-changes-list.html

**Describe the solution you'd like** (*)

To check a plugin compatibility with Intellij Idea, we can use built in Gradle taks: **runPluginVerifier**.
For an example, to check plugin compatibility with the IntelliJ IDEA Ultimate 221.5080.56, we should add next Gradle configuration:

<img width="1471" alt="Screenshot 2022-03-27 at 17 42 36" src="https://user-images.githubusercontent.com/31848341/160286938-a260e6a3-4db5-4f98-ae21-6cd8959fa35b.png">

We will get output in the running terminal:

```
2022-03-27T17:41:29 [main] INFO  verification - Finished 1 of 1 verifications (in 6.1 s): IU-221.5080.56 against com.magento.idea.magento2plugin:4.3.0: Compatible. 13 usages of deprecated API. 7 usages of experimental API. 11 usages of internal API
Plugin com.magento.idea.magento2plugin:4.3.0 against IU-221.5080.56: Compatible. 13 usages of deprecated API. 7 usages of experimental API. 11 usages of internal API
Deprecated API usages (13): 
    #Deprecated interface com.intellij.platform.WebProjectGenerator.SettingsStateListener reference
        Deprecated interface com.intellij.platform.WebProjectGenerator.SettingsStateListener is referenced in com.magento.idea.magento2plugin.generation.php.MagentoProjectPeer.addSettingsStateListener(WebProjectGenerator.SettingsStateListener) : void
    #Deprecated method com.intellij.psi.search.FilenameIndex.getFilesByName(Project, String, GlobalSearchScope) invocation
        Deprecated method com.intellij.psi.search.FilenameIndex.getFilesByName(com.intellij.openapi.project.Project project, java.lang.String name, com.intellij.psi.search.GlobalSearchScope scope) : com.intellij.psi.PsiFile[] is invoked in com.magento.idea.magento2plugin.indexes.FixtureIndex.getDataFixtures(String) : List
    #Deprecated method com.intellij.psi.PsiElement.checkAdd(PsiElement) is overridden
...
```

Or we can view results in the generated html file (./build/reports/pluginVerifier/<version>/report.html):

<img width="1305" alt="Screenshot 2022-03-27 at 17 48 57" src="https://user-images.githubusercontent.com/31848341/160287084-2fdc1d7b-41b3-40a7-abfb-a774d6b4fe2c.png">

**It would be great to add ready to go configuration for running plugin verifier:**

```
runPluginVerifier {
    ideVersions = []
    localPaths = []
}
```

To use it, will be enough to add target version, as on the screenshot above.

**Describe alternatives you've considered**

N/A.

**Additional context**

Mainline branch: 4.3.1-develop

**Comment by doninAtwix** [comment]
@magento I am working on this
