### ISSUE TITLE
Cannot enable magento integration

### ISSUE THREAD

**Issue by Bashev** [magento/magento2-phpstorm-plugin#1067]
**Describe the bug** (*) 
When try to enable module, cannot "save" or "apply" settings and the settings panel cannot be closed. If disable module, i can close settings panel.

**To Reproduce** (*) 

1. Go to 'File'
2. Click on 'Settings'
3. Click on 'PHP'
4. Click on 'Frameworks'
5. Expand 'Magento'
6. Click on 'Enable Magento Integration'
7. Set 'Magento Installation Path'
8. Try to 'Save'

**Expected behavior** (*) 

Settings to be saved and settings modal will close.

**Screenshots**

**Please complete the following information:** (*) 

 - OS: [e.g. MacOS or Ubuntu Linux 20.04]
 - PhpStorm/Intellij version: [e.g. 2019.3.3]
 - Plugin Version: [e.g. 1.0.0]

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @Bashev!

Thank you for your report!
Please, provide more information about your plugin version and PHPStorm version.

Regards,

**Comment by Bashev** [comment]
PhpStorm 2022.1 EAP
Build #PS-221.5080.66, built on March 24, 2022
Licensed to PhpStorm EAP user: Kostadin Bashev
Expiration date: April 23, 2022
Runtime version: 11.0.14.1+1-b2043.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2030M
Cores: 8
Registry:
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true

Non-Bundled Plugins:
    ir.msdehghan.plugins.ansible (0.92)
    com.xiaobing1024.laravel (1.1.1)
    de.espend.idea.php.annotation (8.0.0)
    de.espend.idea.laravel (0.15.4)
    NEON support (0.5.1)
    com.magento.idea.magento2plugin (4.3.0)

**Comment by bohdan-harniuk** [comment]
Hello, @Bashev!

Thank you for providing additional information.
It is a known issue.
We have been already resolved this issue in the scope of https://github.com/magento/magento2-phpstorm-plugin/issues/1058.
I am closing this one as duplicated.

Regards,

**Comment by bohdan-harniuk** [comment]
@Bashev, I can help you to solve this issue temporarily, if you want. 

Because I don't know when we will release this fix.

Regards,

**Comment by Bashev** [comment]
Yes, please!
Thank you
