### ISSUE TITLE
MFTF: Test name autocomplete and reference

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-phpstorm-plugin#107]
### Preconditions (*)
![MFTF PHPStorm plugin (5)](https://user-images.githubusercontent.com/1639941/78462452-59cc6a80-76d2-11ea-9867-5f63bb3810bd.png)

#### Resources

1. Test definitions (1 per file) Test/*Test.xml and Test/*/*Test.xml (`<test name="..."[ extends="..."]>` node) (Example: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/Test/Mftf/Test/AdminLoginSuccessfulTest.xml)

#### Uses

1. `<test extends="...">` refers to `<test name="...">`

### Steps to reproduce (*)
1. When I type `<test extends="` in Test XML

### Expected result (*)
1. I expect the suggestions of existing tests.

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by VitaliyBoyko** [comment]
Hi @lbajsarowicz 
ℹ️ This is already implemented:
![image](https://user-images.githubusercontent.com/20116393/78505054-72dc2680-7779-11ea-87c3-c234c5feb4ed.png)

**Comment by VitaliyBoyko** [comment]
Please check the functionality in the latest develop branch. In case if the functionality does not satisfies acceptance criteria fill free to reopen the issue. Thank you!

**Comment by lbajsarowicz** [comment]
![image](https://user-images.githubusercontent.com/1639941/78505252-92238580-7772-11ea-8e8f-de1caf75ac7b.png)
It does not work properly. It suggests other types of objects than expected.
