### ISSUE TITLE
New layout action doesn't accept valid layout names

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2-phpstorm-plugin#1094]
**Describe the bug** (*) 

Using the action to create a new "Magento 2 layout file" some valid names are not accepted

**To Reproduce** (*) 

1. RIght click a "layout" folder
2. Select "New" and then "Magento 2 layout file"
3. Insert a valid layout name like `cusomter_account` or `hyva_default`

**Expected behavior** (*) 

The expected behavior is to be able to insert a layout name like `my_layout`

**Screenshots**
![immagine](https://user-images.githubusercontent.com/3061752/166662262-a82550f3-22d9-4df4-9dee-a35f3b1a3e7d.png)

**Please complete the following information:** (*) 

 - OS: MacOS
 - PhpStorm/Intellij version: 2022.1
 - Plugin Version: 4.3.1

**Comment by bohdan-harniuk** [comment]
Hello, @slackerzz!

Thank you for your report!
We will try to fix this issue.

Regards,

**Comment by SilinMykola** [comment]
@magento I am working on this
