### ISSUE TITLE
Create an observer for an event doesn't work through the context menu

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#1102]
**Describe the bug** (*) 

It is not possible to create an observer through the context menu

**To Reproduce** (*) 

1. Go to any class with dispatch method
2. Click on event name
3. Check missing "Create a Magento Observer" option

**Expected behavior** (*) 

Should work like this https://github.com/magento/magento2-phpstorm-plugin/wiki/1.0.0-Release#create-an-observer-for-an-event

**Screenshots**

<img width="642" alt="image" src="https://user-images.githubusercontent.com/1055999/169056023-0b1ff4b0-7b09-40db-ab34-e98c9904aa42.png">

**Please complete the following information:** (*) 

 - OS: MacOS
 - PhpStorm version: 2022.1
 - Plugin Version: 4.3.1

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs!

There are few restrictions for this action. It works in this release, but we can check if there is a bug.
Please, attach code of this file here. Not like a screenshot.

Regards,

**Comment by DmitryFurs** [comment]
Hello, @bohdan-harniuk!

This is class [\Magento\Catalog\Model\ResourceModel\Product\Indexer\Eav\Decimal::_prepareIndex()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Eav/Decimal.php#L156)

Is that enough for you?

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs!

Yes, it is enough for me.

Thank you!

**Comment by anzin** [comment]
@magento I am working on this
