### ISSUE TITLE
Automated cache:flush cache:clean

### ISSUE THREAD

**Issue by palandovalex** [magento/magento2-phpstorm-plugin#1104]
**Is your feature request related to a problem? Please describe.**

If you leave the caches, then the state of the project may not correspond to the site's reaction to user actions. Manually starting the cache cleanup can be annoying, and also - you can accidentally forget to do it. But if the caches are turned off at all, then literally EVERY action will have to wait a long time until magento compiles EVERYTHING. And if there are a lot of requests on the page at once?!! Each request will require recompiling everything!

**Describe the solution you'd like** (*)

Thus, it would be extremely useful to add automation: When a file is saved in the IDE, it is necessary to automatically clear all caches. Thanks to this, firstly, when testing the site after making changes, the probability of cache delays will be guaranteed to be eliminated, and secondly, a lot of time will be saved for manually resetting caches and waiting, which is generated by compilations for each request. To implement this - there is no need to manually track these changes - for this you can do integration with this plugin: https://plugins.jetbrains.com/plugin/7177-file-watchers / By the way, the plugin is included in the phpstorm stock, so it is quite possible to rely on it.

**Describe alternatives you've considered**

https://github.com/emcrisostomo/fswatch
But i dont want to install it, i already have an ide - that can do in by itself.

**Additional context**

**Comment by DmitryFurs** [comment]
There is also such an alternative https://github.com/mage2tv/magento-cache-clean

**Comment by bohdan-harniuk** [comment]
Hello @palandovalex!

I believe, that provided by @DmitryFurs alternative is great option to achieve what you requested!

Regards,
