### ISSUE TITLE
Add support for GraphQL schema of a module

### ISSUE THREAD

**Issue by freezy-sk** [magento/magento2-phpstorm-plugin#1105]
**Is your feature request related to a problem? Please describe.**

-

**Describe the solution you'd like** (*)

Added option to create new GraphQL schema file `<module_name>/etc/schema.graphqls`, when choosing to create new file in `etc/`

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by SilinMykola** [comment]
@magento I am working on this
