### ISSUE TITLE
Cannot Save Settings Error

### ISSUE THREAD

**Issue by jeevanshrestha** [magento/magento2-phpstorm-plugin#1115]
Hi, I have installed the plugin in PhpStorm for  Mac. Every time I enable Magento integration and press Ok to save, there is an error saying cannot save settings: Please specify a valid Magento 2 installation path. What makes a Magento 2 folder valid installation path?? 
![Screen Shot 2022-06-16 at 8 53 38 am](https://user-images.githubusercontent.com/1020016/173955618-0c5f11b9-4acd-4175-aa1d-1db4a1917154.png)

**Comment by jeevanshrestha** [comment]
@magento I am working on Magento 2 community edition. I have installed Phpstorm Magento 2 plugin. Inside PHP -> Frameworks -> Magento, I have clicked Enable Magento Integration and entered a valid Magento 2 path. Still cannot save the settings.

**Comment by spyrmp** [comment]
Hello,

I am having the same problem.

Magento2Plugin: 4.3.1
PhpStorm: 2022.1.2 (Build #PS-221.5787.33, built on June 1, 2022)

**Comment by jeevanshrestha** [comment]
Hello,

The issue is solved. I cloned the project from GIT and vendor directory was empty. Once all the files from vendor directory were imported, the error is gone.
