### ISSUE TITLE
Plugin doesn't seem to work in PhpStorm 2022.1.2

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2-phpstorm-plugin#1118]
After upgrading phpStorm to 2022.1.2 the Magento2 plugin stopped working.
No context menu with Magento2 related items appear, neither in the project browser nor the editor context menu.

**Describe the bug** (*) 

After opening phpStorm 2022.1.2 with a Magento2 project, project browser context menu items related to Magento2 don't show up. 

**To Reproduce** (*) 

Open phpStorm 2022.1.2, open any magento2 project, make sure the Magento2 plugin is loaded and activated for this project. In the project browser, go to app/code and right click to open the dropdown menu. It should show below the menu item "New" some magento2 specific options (you can spot them by the magento icon in front):
Magento2 Module
Dependency Injection XML File (di.xml)
in phpStorm 2022.1.2 these menu items are missing

Same in the editor pane:
open any class file in the editor, got to a public function, right click on the line with the function definition and right click:
the downdown menu should show least 3 menu items related to magento2:
Create a new Plugin
Override this class by a new Preference
Create a new Web API declaration for this method
in phpStorm 2022.1.2 these menu items are missing

**Expected behavior** (*) 

Menu items should appear as they have done before in phpStorm 2021.3.3.
When installing a older phpStorm (2021.3.3) and repeating the steps above, all context menu items reappear again.

**Screenshots**

<img width="599" alt="Project Browser Options as in phpStorm 2021.3.3" src="https://user-images.githubusercontent.com/5113496/174425299-cf766c40-029c-47b9-81ec-dd7ca25eb0e8.png">
<img width="605" alt="Code editor options as in phpStorm 2021.3.3" src="https://user-images.githubusercontent.com/5113496/174425315-74a17bdf-8606-4b5a-8fc9-f33cf332f7dc.png">

**Please complete the following information:** (*) 

 - OS: macOS Big Sur 11.6.7
 - PhpStorm/Intellij version: 2022.1.2 (not working) and 2021.3.3 (working)
 - Plugin Version: 4.3.1

**Comment by bohdan-harniuk** [comment]
Hello, @stephansteiner!

There is a breaking changes in the provided PhpStorm version.
We are thinking about a new release that will support this version and of course it won't support previous versions...but we do not have enough closed tasks to go in live.

We will discuss what to do next.

Thank you for your report.

**Comment by bohdan-harniuk** [comment]
As a temporary fix you can downgrade your PHPStorm version.

**Comment by bohdan-harniuk** [comment]
Hello, @stephansteiner!

This issue was fixed by JetBrains long time ago. 
Sorry, for late notice.

Regards,
