### ISSUE TITLE
[Generation] Add data patch and observer generators

### ISSUE THREAD

**Issue by AboElnoor** [magento/magento2-phpstorm-plugin#1139]
**Is your feature request related to a problem? Please describe.**
No, related issue: [#861 ](https://github.com/magento/magento2-phpstorm-plugin/issues/861)

Creating data patches manually

**Describe the solution you'd like** (*)

To add the ability to add data patch singularly when I click on setup directory for example

**Comment by AboElnoor** [comment]
Hi @bohdan-harniuk ,
Creating observers is also missing individually. I believe it needs to show up too.
Regards

**Comment by bohdan-harniuk** [comment]
Hello, @AboElnoor!

Thank you for the great ideas!
We'll definitely add those generators in the near time.

Regards,

**Comment by anzin** [comment]
@magento I am working on this
