### ISSUE TITLE
[Context-generation] Extend the README.md file generation

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1141]
**Is your feature request related to a problem? Please describe.**

We need to extend the README.md file generation through the context menu. 
For now it is raw and can be more useful.

**Describe the solution you'd like** (*)

1. We need to check, if the README.md file is already generated we should not show action. 
2. We should add a new code include, to be able generate project-specific README.md files

<img width="997" alt="Screenshot 2022-08-08 at 13 57 54" src="https://user-images.githubusercontent.com/31848341/183403219-549c892d-f90f-4ad4-80e7-ce5f7a0518a9.png">
<img width="915" alt="Screenshot 2022-08-08 at 13 55 34" src="https://user-images.githubusercontent.com/31848341/183403226-1e3759fb-16f3-4371-b1a5-cff08c6c3015.png">

Current content of the new code include will be:

```
<!---
    You can describe your module here.
    We recommend that you add the following information:
     - implementation details: why and how to use the module, preferably with some example scenarios
     - any dependencies (usually other modules but could be any important dependencies, libraries, etc)
     - extension points, APIs, plug-ins, etc
     - any introduced events
-->
```

**Additional context**

**Mainline branch:** 4.4.0-develop

**Comment by makzef** [comment]
@magento I am working on this
