### ISSUE TITLE
[Settings] Could not enable integration for the projects with different names

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1144]
**Describe the bug** (*) 

We have to find the reason why this doesn’t work for all cases. If some technical issues occur, we should show specific error message, not just: `Please specify a valid Magento 2 installation path`. From this message I assume that the folder name is not valid. If the root of the issue is different, we should see corresponding message. If it is because of the name itself -> we **MUST NOT** have such limitation about project naming.

**To Reproduce** (*) 

1. Go to the plugin settings
2. Fill the **Magento installation path:** field with the `**TEST_INVALID_NAME_FOR_M2**` value.
3. Click on **Apply** or **Save**
4. See error: `Please specify a valid Magento 2 installation path`

**Expected behavior** (*) 

Any valid directory should work for us or specific error message should be shown.

**Screenshots**

<img width="990" alt="Screenshot 2022-08-12 at 14 24 29" src="https://user-images.githubusercontent.com/31848341/184345312-80d6eba9-b4e7-4440-9471-e4f45e527c80.png">

**Please complete the following information:** (*) 

 - OS: **any**
 - PhpStorm/Intellij version: **any**
 - Plugin Version: **any**

**Additional context**

**Mainline branch:** 4.4.0-develop

**Comment by makzef** [comment]
@magento I am working on this
