### ISSUE TITLE
[Bug] README.md template include is not working for project level

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1156]
**Describe the bug** (*) 

Custom template includes are not working for project level.

**To Reproduce** (*) 

1. Go to `Preferences > Editor > File and Code Templates`
2. Click on 'Includes' tab
3. Choose 'MD File Description'
4. Copy content of this include
5. Choose the Project schema instead of the Default
6. Paste content and make some change here
7. Generate the README.md file and check if right content generated for include

**Expected behavior** (*) 

If project specific template include is specified, it is used during files generation instead of Default scheme.

**Screenshots**

https://user-images.githubusercontent.com/31848341/188580576-7b644fb3-5dd4-49c4-a9cd-1add514871fa.mp4

**Please complete the following information:** (*) 

 - OS: any
 - PhpStorm/Intellij version: any
 - Plugin Version: 4.3.1

**Additional context**

**Mainline branch:** 4.4.0-develop

**Comment by DmitryFurs** [comment]
Hello @bohdan-harniuk!

Do we need to follow the README.md template described here?
https://github.com/magento/devdocs/wiki/Magento-module-README.md
Should you include this template in the plugin?

Thanks!

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs !

We'll discuss it.

Thank you!

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs !

New task created for your suggestion: https://github.com/magento/magento2-phpstorm-plugin/issues/1174

Regards,
