### ISSUE TITLE
[Context-Generation] Add a new context action to generate an events.xml file

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1175]
**Is your feature request related to a problem? Please describe.**

We should be able to generate an **events.xml** file through the context actions.

**Describe the solution you'd like** (*)

**Acceptance Criteria:**

- New context action should be added
- It should inherit the `com.magento.idea.magento2plugin.actions.context.AbstractContextAction`
- Target area should be asked

**Additional context**

Mainline branch: 5.0.0-develop

**Comment by SilinMykola** [comment]
@magento I am working on this
