### ISSUE TITLE
Change Magento icons to GraphQL icons for GraphQL related actions

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1195]
**Is your feature request related to a problem? Please describe.**

It would be easier to find GraphQL related actions if they would be marked with the GraphQL icons.

**Describe the solution you'd like** (*)

Change icons for next actions:

- Magento 2 GraphQL Schema File
- Magento 2 GraphQL Resolver

<img width="807" alt="Screenshot 2022-09-16 at 19 24 59" src="https://user-images.githubusercontent.com/31848341/190686295-d0828612-b8c8-430e-9882-5445a7adc559.png">

**Additional context**

**Mainline branch:** 4.4.1-develop

**Comment by anzin** [comment]
@magento I am working on this
