### ISSUE TITLE
[Bug] Possible NullPointerException exception in actions/generation/dialog/InjectAViewModelDialog.java:145

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1206]
**Describe the bug** (*) 

PhpStorm highlights possible NullPointerException exception in actions/generation/dialog/InjectAViewModelDialog.java:145.

**Expected behavior** (*) 

We should add a check for null value here.

**Please complete the following information:** (*) 

 - OS: any
 - PhpStorm/Intellij version: any
 - Plugin Version: 4.4.0

**Additional context**

**Mainline branch:** 4.4.1-develop

**Comment by Mgonzalez-droid** [comment]
I would be interested in taking on this issue

**Comment by bohdan-harniuk** [comment]
Hello, @Mgonzalez-droid!

You can proceed with it.

**Comment by Mgonzalez-droid** [comment]
Thank you! @bohdan-harniuk

**Comment by bohdan-harniuk** [comment]
@Mgonzalez-droid, please, assign it on yourself if you work on it.

**Comment by Mgonzalez-droid** [comment]
It may be a security setting but I can't assign myself. The option seems to be disabled for me. Could you assign it to me?

**Comment by Mgonzalez-droid** [comment]
It seems it is due to me not being a collaborator @bohdan-harniuk

**Comment by bohdan-harniuk** [comment]
@Mgonzalez-droid, just use what is said here above

<img width="952" alt="Screenshot 2022-09-21 at 14 43 15" src="https://user-images.githubusercontent.com/31848341/191495392-1f732650-4edb-4d75-a619-9c3967a75b9b.png">

**Comment by Mgonzalez-droid** [comment]
@magento I am working this

**Comment by pranjal09J** [comment]
Hello @bohdan-harniuk I am new to Open Source and would like to contribute in this issue.

**Comment by bohdan-harniuk** [comment]
Hello, @pranjal09J!
Great to hear that. @Mgonzalez-droid has already taken this issue. So, let him finish this issue, you can take another one with the **good first issue** label.
Regards,

**Comment by pranjal09J** [comment]
Thanks. I will look for some other issue.

**Comment by ishu-thakur** [comment]
Hello @bohdan-harniuk I am new to open source and would like to contribute in this project .
