### ISSUE TITLE
Upgrade org.jetbrains.intellij to the version 1.9.0 (2022.2.3)

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#1211]
**Is your feature request related to a problem? Please describe.**

We should update the `org.jetbrains.intellij` plugin to 1.9.0 (2022.2.3) version.

**Describe the solution you'd like** (*)

Make upgrade and all necessary changes to get it working.

**Additional context**

**Mainline branch:** 5.0.0-develop

**Comment by VitaliyBoyko** [comment]
Done
