### ISSUE TITLE
Missing EntityRepositoryInterface when creating a new Entity 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2-phpstorm-plugin#1216]
**Is your feature request related to a problem? Please describe.**

When creating a new entity via the plugin, the repository interface and class is not created. It's not a problem, just an omission and it would be nice to have it. 

![image](https://user-images.githubusercontent.com/20220341/192607307-39906ac9-3b56-4169-85f2-380aa83a3c4b.png)

On the contrary it creates three interfaces for handling persistence and retrieval 

For example for an entity called `Category`

It generates

```
Api/DeleteCategoryByIdInterface.php
Api/GetCategoryListInterface.php
SaveCategoryInterface.php
```

So whenever fetching a single category, we need to use the Api/GetCategoryListInterface.php and there's no single getCategoryByIdInterface. 

The repository class encompassed all these interfaces with a single class to inject for handling those operations. 

**Describe the solution you'd like** (*)

Create the repository interface and class or create the GetEntityByIdInterface as well to have full capabilities like with a repository class. 
I would still prefer having a standalone repository class as it makes it more understandable what it does. Normally when I want to do CRUD operations, I would type the Entity Name followed by the word Repository and the IDE would automatically find the class for me very easily. This way it's not so convenient. 

**Describe alternatives you've considered**

I've been using a customized version of https://github.com/staempfli/magento2-code-generator.git for this and it can generate repositories too. 
It also generates factory classes too for easier code completion when generated classes are not yet generated.  

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @ioweb-gr!

Repositories is older way to deal with the CRUD operations. CQRS pattern was used as a best practice.

Each Service should follow the [CQRS](https://martinfowler.com/bliki/CQRS.html) semantic and represent Command or Query, but not both.

Queries: Return a result and do not change the observable state of the system (are free of side effects).
Commands: Change the state of a system but do not return a value (return void).
 
More Information and Documentation
More examples of designing Service Contracts for Magento 2 could be found in the scope of [Multi-Source Inventory (MSI)](https://github.com/magento-engcom/msi) project. The project [wiki](https://github.com/magento-engcom/msi/wiki) provides information and discussions of the most interesting architectural changes implementing these best practices and Service Contracts.

We recommended reviewing the [Magento Service Isolation](https://github.com/antonkril/architecture/blob/fdcfafe1d6187f9abaf18af9eec7c10e8067a637/design-documents/service-isolation.md) design document which describes the Modularity approach being introduced to Magento codebase which would help to split the Monolith on independent and isolated set of Services. See DevDocs [Service Contracts](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#64-service-contracts-application-layer) in the Technical Guidelines for development guidelines and requirement.

Regards,
