### ISSUE TITLE
How to set custom vendor dir for magento2 plugin

### ISSUE THREAD

**Issue by roman204** [magento/magento2-phpstorm-plugin#1217]
**Is your feature request related to a problem? Please describe.**
With Magento 2.4.5 some filenames of mtf are too long for encrypted drives. To install magento anyway i have to mount a non encrypted dir outside of my home dir to the docker container as vendor folder. But then i cannot enable magento2 plugin because the vendor dir is not found under the given folder in magento2phpstorm plugin configuration. 
The error message on the following screen appears which says: "Vendor dir is corrupt or missing in the current Magento 2 installation path" .
Even if i put the custom vendor dir to my project in phpstorm the error appears. 
![image](https://user-images.githubusercontent.com/584168/192740407-56f868ed-3bdb-4f6e-bf73-1155717272b4.png)

Anybody got a solution for that? Is it possible to give a "custom vendor dir" to phpstorm which is respected by the magento2 plugin?

**Describe the solution you'd like** (*)

The magento2 phpstorm plugin respects the "content root dir" settings in phpstorm and looks for "custom vendor dirs".

**Describe alternatives you've considered**

**Additional context**

a search in the sourcecode of this plugin leads to some interessing code where "custom vendor dir" is used but it seems to be for modules and not for the whole project: https://github.com/magento/magento2-phpstorm-plugin/search?q=vendor+dir
but maybe this is useful

**Comment by bohdan-harniuk** [comment]
Hello, @roman204!

The **vendor** dir doesn’t make sense if it is empty. You should have Magento modules (framework and other) to enable integration. 
Please, check it out.

Regards,

**Comment by roman204** [comment]
Hi, @bohdan-harniuk ,
the vendor dir inside the project folder is empty but not the "custom vendor dir" which i have configured. As i mentioned i have to put it outside of the encypted part of the harddisk. It would be nice to have a setting for "custom vendor dir".

**Comment by bohdan-harniuk** [comment]
@roman204, will be done in the next release.
Can I as you to test our solution before releasing it?

**Comment by bohdan-harniuk** [comment]
Also, please, share how to configure a custom vendor dir in the Magento, so we can auto-populate it during first project configuration.
