### ISSUE TITLE
Add included vendor modules with directory namespace to target moduile

### ISSUE THREAD

**Issue by mvenghaus** [magento/magento2-phpstorm-plugin#1275]
**Is your feature request related to a problem? Please describe.**

When contributing to an open source module or developing my own composer module I do the following.
- i cancel the exclusion from vendor/name/module/
- add the the src path and add vcs
- set the namespace in the directory settings in phpstorm

This way it's really easy to switch branches and test the composer configuration.

One thing that is missing is that this module is not shown in target module when I for example want to create a plugin.

**Describe the solution you'd like** (*)

It would be nice if all directories with a namespace added in the directory settings would be scanned also and provided as a target module in the settings.

**Comment by VitaliyBoyko** [comment]
duplicate #1263
