### ISSUE TITLE
Test coverage. Cover module name completion and reference in the module.xml by tests

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#131]
### The following functionality need to be covered:
![image](https://user-images.githubusercontent.com/20116393/78929486-265f5680-7aab-11ea-96a3-d2e9abde9219.png)

**Comment by vasilii-b** [comment]
@VitaliyBoyko I'll cover you 😌

**Comment by VitaliyBoyko** [comment]
Hi @vasilii-b 
Hold on this one, I'm changing the approach of adding test data.

**Comment by vasilii-b** [comment]
@VitaliyBoyko, roger that!

**Comment by VitaliyBoyko** [comment]
Hi @vasilii-b 
Please review the changes and proceed. Thank you!

**Comment by drpayyne** [comment]
@magento I am working on this
