### ISSUE TITLE
Feature request: Add navigation for JS files in require section

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2-phpstorm-plugin#136]
Would be great to have a following feature:
in PhpStorm when you're clicking on any of declared components - open that component.

Example: 
![image](https://user-images.githubusercontent.com/1873745/79002425-21f17700-7b59-11ea-93d9-9333562719a6.png)

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/frontend/web/js/view/compare-products.js#L7-L11

**Comment by VitaliyBoyko** [comment]
HI @ihor-sviziev 
It's already implemented. See the corresponding or #25. Also, you can check the latest develop branch.  

Thank you!
