### ISSUE TITLE
Action/Code Generation. New CLI command Generation

### ISSUE THREAD

**Issue by roma-glushko** [magento/magento2-phpstorm-plugin#142]
Add action and templates for generating CLI commands.

- Right-click on the module directory
- Create a CLI command is accessible in the Module Files group
- Click on the action
- Create a CLI command dialog is shown
- Dialog contains: CLI Classname, CLI parent directory, CLI name in bin/magento and description
- After filling out the required fields and click the Ok button, CLI is created and registered in the di.xml
- CLI command class is opened right after generating

**Comment by coderimus** [comment]
Hi @roma-glushko @VitaliyBoyko 
I would be great if you could assign me to this feature request. I want to take part :)

Looks like I do not have permissions to assign myself.

**Comment by roma-glushko** [comment]
@coderimus thank you for help 🙌 
I also seem to lose my rights to manage assignments/labels for some reasons 🤔 
@VitaliyBoyko leaving this for you

**Comment by VitaliyBoyko** [comment]
@coderimus Done!
