### ISSUE TITLE
Reference navigation. Reference: disabled plugin declaration -> plugin declaration

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#146]
### Preconditions (*)
* 2 modules in the system: Module_Foo and Module_Bar
* Module_Foo di.xml declares a plugin
``` 
<type name="SomeTarget">
    <plugin name="plugin_id" type="SomePlugin" />
</type>
``` 
* Module_Bar di.xml disables a plugin
``` 
<type name="SomeTarget">
    <plugin name="plugin_id" disabled="true" />
</type>
``` 

### Acceptance criteria
* a reference navigation element is added to attribute name of the plugin tag with attribute `disabled="true"` to easily navigate form disabling declaration to original declaration, in this case, from `Module_Bar/etc/di.xml` to `Module_Foo/ets/di.xml`.
* the functionality is covered by tests

**Comment by drpayyne** [comment]
@magento I am working on this
