### ISSUE TITLE
phpstorm meta plugin file

### ISSUE THREAD

**Issue by ragboyjr** [magento/magento2-phpstorm-plugin#15]
By adding the following `.phpstorm.meta.php` into the root of the repo, you can get better code completion when using magento's DI ObjectManager get method.

```php
<?php

namespace PHPSTORM_META
{
    override(\Magento\Framework\ObjectManagerInterface::get(0), map(['' => '@']));
}
```

It looks like this file can be easily added into the system via the library root feature shown here: https://github.com/artspb/phpstorm-library-plugin

**Comment by davidhiendl** [comment]
This functionality would be useful, but you should add support for `->create(...)` as well as `->get(...)`:

```php
namespace PHPSTORM_META {
    override(\Magento\Framework\ObjectManagerInterface::get(0), map(['' => '@']));
    override(\Magento\Framework\ObjectManagerInterface::create(0), map(['' => '@']));
}
```

**Comment by danmooney2** [comment]
Would this go in your Magento project or would it be inside the plugin itself?

**Comment by davidhiendl** [comment]
I can be provided via the plugin (which would be the optimal solution) but you can also add it manually to your project by creating a file at:
`$PROJECT_ROOT/.phpstorm.meta.php/<filname of your choosing>.php`
such as `$PROJECT_ROOT/.phpstorm.meta.php/di-autocomplete.php`
