### ISSUE TITLE
Create an Observer action is missing for _eventManager (field with underscore preffix)

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#150]
It works for a field without an underscore ✅ :
![image](https://user-images.githubusercontent.com/20116393/79203536-da623800-7e43-11ea-820a-2a0131279700.png)

It doesn't work for the field with the underscore prefix ⛔ :
![image](https://user-images.githubusercontent.com/20116393/79203625-f9f96080-7e43-11ea-8d22-2dab1ae65e2a.png)

### Steps to reproduce (*)
1.  Right-click to a parameter of dispatch call of `eventManager` that named with the underscore.

### Expected result (*)
1. Action appears

### Actual result (*)
Action is missing

**Comment by AndreyChorniy** [comment]
Hey @VitaliyBoyko, I would like to try to start my journey with this issue
