### ISSUE TITLE
phpStorm Directories are reset after reindexing 

### ISSUE THREAD

**Issue by aivorisk** [magento/magento2-phpstorm-plugin#1501]
**Context:**

- The magento2 phpstorm plugin is enabled for the project.

**Steps to reproduce:**

1. Change directories in phpStorm configurations.
2. Open another project with magento2 phpstorm plugin enabled.
3. Open the where directories were changed.
4. Directories are reset to plugin initial configurations.

**Comment by joinAdeoWeb** [comment]
Found the problem. It has nothing to do with the plugin.

Unchecking the setting in **PHP -> Composer -> Synchronize IDE Settings with composer.json** fixed the problem.

Close the thread.

**Comment by aivorisk** [comment]
Found the problem. It has nothing to do with the plugin.

Unchecking the setting in **PHP -> Composer -> Synchronize IDE Settings with composer.json** fixed the problem.

Closed the issue.
