### ISSUE TITLE
Custom theme couldn't be detected

### ISSUE THREAD

**Issue by webcreative24** [magento/magento2-phpstorm-plugin#1517]
**Describe the bug** (*) 

I've created a custom theme in the following folder: app/design/frontend/Vendor/custom-theme. Everything works fine but Magento PHPStorm plugin cannot detect the custom theme when I tried to override core module template 

**The problem occurs that there is a dash in my custom theme name**

**To Reproduce** (*) 

1. Navigate to any of Magento core template files. Ex.: vendor/magento/module-catalog/view/frontend/templates/product/listing.phtml
2. Click on 'Override file in a project theme'
3. Click on the Target Theme list dropdown
4. The dropdown is empty

**Expected behavior** (*) 

The Target theme dropdown should be populated

**Screenshots**

![image](https://user-images.githubusercontent.com/13699502/231884085-69781204-12a2-4e71-bf6f-506f05426acd.png)

**Please complete the following information:** (*) 

 - OS: Ubuntu Linux 20.04
 - PhpStorm 2022.3.2
 - Plugin Version: 5.0.1

**Comment by webcreative24** [comment]
@magento I am working on this

**Comment by webcreative24** [comment]
@magento add to contributors team

**Comment by webcreative24** [comment]
https://github.com/magento I am working on this

**Comment by webcreative24** [comment]
@magento I am working on this

**Comment by DmitryFurs** [comment]
Hello @VitaliyBoyko 

It seems that now the theme should start with a lowercase letter `frontend/Vendor/theme`, but in some projects there are themes starting with a capital letter `frontend/Vendor/Theme`. In such cases, the themes are also not detected.

The documentation does not say that the theme should start with a lowercase letter, it just uses the `<theme>` placeholder.

But there is such a note:

> The folder name conventionally matches naming used in the theme's code: any alphanumeric set of characters, as the vendor sees fit, is acceptable. This convention is merely a recommendation, so nothing prevents naming this directory in another way.

https://developer.adobe.com/commerce/frontend-core/guide/themes/create-storefront/#create-a-theme-directory

Thanks!

**Comment by VitaliyBoyko** [comment]
Thanks @DmitryFurs 

I'll check the 'frontend/Vendor/Theme' case.

**Comment by VitaliyBoyko** [comment]
'frontend/vendor/theme' is also a possible case and needs to be covered as well.

Little too much freedom, I would say :smile:

**Comment by DanieliMi** [comment]
This seems to be still an issue in Version 5.1.1. I have three themes:
* `app/design/frontend/Vendor/Theme1`
* `app/design/frontend/Vendor/Theme2`
* `app/design/frontend/Vendor/Theme3`
None of these are displayed, only the Hyvä themes:  
![ksnip_20230613-124152](https://github.com/magento/magento2-phpstorm-plugin/assets/31039652/934b1eb0-d8d8-42d9-a671-1ddc5794dda6)  
It seems only themes in `vendor/` are detected.

**Comment by sdouma** [comment]
ok so here is the current version committed
`[a-z]+/[a-zA-Z0-9_]+/[a-z][a-zA-Z0-9_]+`
https://regex101.com/r/a7GafQ/1

This should be the updated? 
https://regex101.com/r/a7GafQ/2
`[a-z]+/[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+`

Or will this be allowing any valid folder/file character?
