### ISSUE TITLE
Compare templates feature supporting hyva compatibility modules

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2-phpstorm-plugin#1600]
**Is your feature request related to a problem? Please describe.**

To reproduce the issue, you need to have the following setup:
- custom theme based on Hyva
- third party module
- Hyva compatibility module for the third party module
- override of a template based on the hyva compatibility module in your theme

If you now open the overridden template and use the "compare overridden file with source" functionality, your template is falsely compared to the original template from the third party module, not the one from the hyva compatibility module.

**Describe the solution you'd like** (*)

I would love to compare my override with the actual overridden template from the compatibility module.

**Comment by amenk** [comment]
@norgeindian That sounds interesting, does this work now?

**Comment by norgeindian** [comment]
@amenk, I closed this, because I created this issue in the wrong repository. The whole comparing logic is already implemented in the Atwix module, so I opened an issue there: https://github.com/Atwix/phpstorm-plugin-feedback/issues/30

**Comment by amenk** [comment]
@norgeindian Ah, cool, thanks for pointing us to the Atwix module :-)
