### ISSUE TITLE
Action/Code Generation. Add copyrights to XML files

### ISSUE THREAD

**Issue by roma-glushko** [magento/magento2-phpstorm-plugin#174]
Currently, all XML files don't contain copyrights in the templates. Here is an example of one template:

```tmp
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    #if (${SEQUENCES})
        <module name="${PACKAGE}_${MODULE_NAME}">
            <sequence>
                ${SEQUENCES}
            </sequence>
        </module>
    #else
        <module name="${PACKAGE}_${MODULE_NAME}" />
    #end
</config>
```

We need to include copyrights to XML files like we are doing this for PHP class templates. Here is an example of the expected result after the generation:

```xml
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Magento_Catalog" >
        <sequence>
            <module name="Magento_Eav"/>
            <module name="Magento_Cms"/>
            <module name="Magento_Indexer"/>
            <module name="Magento_Customer"/>
        </sequence>
    </module>
</config>

```
Copyright should be configurable like we have it in PHP class generation

**Comment by VitaliyBoyko** [comment]
Hi @roma-glushko 
Intellij has for that out-of-box functionality.
Copyrights being added automatically if they are configured in the system.

* Configure copyright profile:
![image](https://user-images.githubusercontent.com/20116393/79685782-ff8be780-8243-11ea-8f01-cd0cb6f76d79.png)

* Configure scope:
![image](https://user-images.githubusercontent.com/20116393/79685790-0f0b3080-8244-11ea-9afd-736921d2ea1e.png)

* Test (eg. Override class by a Preference)
![image](https://user-images.githubusercontent.com/20116393/79685802-2518f100-8244-11ea-808b-8553c05bbd13.png)

Let me know if the functionality does not satisfy your requirements. Thank you!

**Comment by roma-glushko** [comment]
@VitaliyBoyko brilliant 🙌 works for me
Leaving this task as reference for others

**Comment by serzhik** [comment]
This copyright is not in Magento style for XML files:

```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
```
