### ISSUE TITLE
Action/Code Generation. Add new Magento Admin menu item generator

### ISSUE THREAD

**Issue by roma-glushko** [magento/magento2-phpstorm-plugin#177]
Add action and templates for generating new menu items to Magento Admin main menu.

- Right-click on the module directory
- Create a menu item is accessible in the Module Files group
- Click on the action
- Create a menu item dialog is shown
- The actions dialog contains `Menu Item Title`, `Menu Item Action`, `Menu Item Resource`, visual representation of the current menu tree to select the `parent menu node` from.
- After filling out the required fields and click the Ok button, menu.xml is created according to the dialog data
- menu.xml file is opened right after generation

**Comment by VitaliyBoyko** [comment]
Implemented in the scope of the UI components tasks
