### ISSUE TITLE
Very aggressive auto completion in XML

### ISSUE THREAD

**Issue by lfolco** [magento/magento2-phpstorm-plugin#20]
When typing in an XML file, the auto completion looks to be set to auto fill when you press the space bar. A lot of times you don't need to fill in class paths, etc. when typing between tags. Is there a way to tone this down a bit, give it a delay of some sort? I always have to delete autofilled text in XML. 

![screencast 2019-04-07 12-08-08](https://user-images.githubusercontent.com/1709329/55686355-3390b500-592e-11e9-965e-b0ee46f864a2.gif)

In the screencast, I was trying to type _Custom cache_, and when I typed the word _cache_ and then hit the space bar, it force autofilled the only entry it could find:

![image](https://user-images.githubusercontent.com/1709329/55686384-92eec500-592e-11e9-9249-506b82469566.png)

The only way to make it not do that is to hit the escape key after each word.

Not sure if this is something in PhpStorm (the fact that it selects the only entry it finds and fills it), but after disabling the plugin, the behavior does not occur.

**Comment by enriquepiatti** [comment]
It's strange because Magicento is not giving autocomplete for Label node, I think could be something from PhpStorm. Are you sure you don't get any help with Magicento disabled? because the autocmplete looks mixed too, normally when Magicento adds atucomplete is very specific (for example only .phtml paths, or only class names, etc)

**Comment by lfolco** [comment]
I tested with all Magento plugins disabled, then reenabled one by one, and it's the Magento 2 plugin. I don't have Magicento installed for Magento 2, only Magento 1.

**Comment by enriquepiatti** [comment]
But you are working with Magento2? then you should disable Magicento1 (normally is disabled automatically if is not a Magento1 project).
Try disabling it from Magicento settings (not from PhpStorm plugins). Is that solving the problem?

**Comment by lfolco** [comment]
It had not been enabled for this project; even so I had disabled Magicento and the behavior still occurred.

**Comment by enriquepiatti** [comment]
OK, I will take a look, I think the only workaround for now then is to disable Magicento1 when you work with Magento2 :/

**Comment by lfolco** [comment]
The behavior still occurs when I disable Magicento completely.

**Comment by enriquepiatti** [comment]
You mean from PhpStorm plugins? if it occurs even after that then is not related with Magicento.

**Comment by lfolco** [comment]
I thought this repo was for the Magento 2 plugin, not Magicento?

![image](https://user-images.githubusercontent.com/1709329/55799952-8d18f100-5aa0-11e9-84f0-c373fbb3731d.png)

**Comment by enriquepiatti** [comment]
haha sorry @lfolco you are right, I've received this in my email and get confused :(

**Comment by lfolco** [comment]
No worries, I figured that was what happened :)

**Comment by lfolco** [comment]
This seems to be native to PhpStorm.
