### ISSUE TITLE
Add reference navigation and completion for `instance` and `method` attributes in cron.xml

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#212]
We need to add reference and completion to the instance and the method attributes.
![image](https://user-images.githubusercontent.com/20116393/80093919-09785800-856e-11ea-8767-6e29938713d9.png)

### Expected result (*)
1. Completion and reference is added
2. Functionality is covered by tests

**Comment by VitaliyBoyko** [comment]
The reference seems to be working, need to adjust completion and tests.

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, looks like a couple PRs were made without referencing this issue. Hence this can be closed

- https://github.com/magento/magento2-phpstorm-plugin/pull/280
- https://github.com/magento/magento2-phpstorm-plugin/pull/310

**Comment by VitaliyBoyko** [comment]
Thanks. Sure
