### ISSUE TITLE
Add a QuickFix for GraphQL schema inspection

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#217]
![image](https://user-images.githubusercontent.com/20116393/80201205-73573700-862c-11ea-98b5-6d01f690470a.png)

If resolver does not exist, there should be available a Quick Fix for adding it using `com.magento.idea.magento2plugin.actions.generation.generator.ModuleGraphQlResolverClassGenerator`.

**Comment by drpayyne** [comment]
Hi @konarshankar07 are you working on this issue? If not, I'd like to work on this. Thank you!

**Comment by drpayyne** [comment]
@magento I am working on this
