### ISSUE TITLE
Product images do not display despite Product Edit image roles

### ISSUE THREAD

**Issue by jlballes** [magento/magento2-phpstorm-plugin#2367]
**Is your feature request related to a problem? Please describe.**

I have found [this issue](https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/storefront/product-images-do-not-display-despite-product-edit-image-roles) in Adobe documentation and my Magento instance is affected.
Is there any solution in order to this issue does not happen again?

**Describe the solution you'd like** (*)

It would be great a patch to solve this problem

**Describe alternatives you've considered**

**Additional context**
I am using Adobe Commerce on premise, ver. 2.4.5-p10

Thanks

**Comment by VitaliyBoyko** [comment]
@jlballes 

This repo is not a Magento Core repo. Please open the issue here https://github.com/magento/magento2
