### ISSUE TITLE
PHPStorm not open on Magento root

### ISSUE THREAD

**Issue by dmanners** [magento/magento2-phpstorm-plugin#244]
**Describe the bug** (*) 

Using the PHPStorm plugin when having PHPStorm open a level above the Magento root seems to not show target modules when creating a plugin or any other option with the "Target Module" dropdown.

**To Reproduce** (*) 

1. Setup PHPStorm so that it is open one directory above the Magento root. E.g. ProjectName->src when src is the Magento root and project name contains other project-related files.
1. Enable module,
1. Go to a class in Magento,
1. Right-click on the method name and select "Create a Plugin",

**Expected behavior** (*) 

All modules under app/code to be shown in the "Target Module" drop-down

**Screenshots**

![PHPStormBug](https://user-images.githubusercontent.com/1572836/81085300-59083d80-8ef7-11ea-933d-f05c329bbd72.png)

**Please complete the following information:** (*) 

 - OS: Ubuntu
 - PhpStorm/Intellij version 2020.1.1
 - Version: 1.0.0

**Additional context**

I have tested this by using the same directory but opening only the Magento root. It could be that I do not have something correctly setup with the src folder but all the URNs are setup and navigation from the plugin seems to be working as expected.

**Comment by coderimus** [comment]
Hello @dmanners !
Thank you for your report. I made a test according to your request and this is the result:
1. I created a folder
2. Add the `scr` folder into it and in it create a new `Magento CE` project
3. Open PHPStorm
4. Target project root for PHPStrom on the src level so the Magento project is one level under
5. Create 2 modules in the `app/code`
6. Tried to create a plugin
7. All 2 new modules appeared in the module selection dropdown
![image](https://user-images.githubusercontent.com/5318512/81097028-f53e3e80-8f0f-11ea-9db0-64d543818f1d.png)

I think that the problem, possibly, in the settings of your project. Please, check the `Magento install path` and if the problem would not be solved or my test was incorrect ping me :)

Example of my settings for `Magento install path`:
![image](https://user-images.githubusercontent.com/5318512/81097204-38001680-8f10-11ea-9c6d-12197c18d15e.png)

**Comment by dmanners** [comment]
Thanks for looking at this @coderimus I have these settings and that also seems fine as it picks up the version of Magento as well. Like I said if I just open the src directory as a PHPStorm project everything works fine but when I have the main project root open and not Magento root it does not work :(

Are there any other PHPStorm seetings like source root that I need to take care of?

![phpstorm-magentoroot](https://user-images.githubusercontent.com/1572836/81142623-6dd4e780-8f70-11ea-9afe-240941eb9f65.png)

**Comment by dmanners** [comment]
Ah I think I have found the problem with it. I have the PHPStorm project setup in a different directory as the actual code. And when I just open the directory with the code even with the multiple levels then it works well. I wonder if the module does not work with my setup.

Steps to get my setup:

1. In PHPStorm create a new project and put it in any place. For me it's `/home/dmanners/PhpstormProjects/ProjectName`.
1. Add the source root via the settings in PHPStorm and point to another directory. Using `Settings->Directories` and click "Add Content Root".

The reason I did this was in my old setup I had the content linked over a samba share. Technically now I do not need to run it this way but can simply put the project and content in the same place. But old habits die hard it seems.

This means I have my .idea settings under `/home/dmanners/PhpstormProjects/ProjectName/.idea`
but for example, some of the files are not set up correctly. The modules file is actually empty and not the same as if I open the folder directly.

**Comment by coderimus** [comment]
Hello @dmanners ! Thank you for the detail explanation. It is an interesting case 👍  Let me reproduce it and I will return to you with an answer in few days :)

**Comment by okorshenko** [comment]
@magento I am working on this

**Comment by coderimus** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Hello, @dmanners!

Is it still actual for you?
The settings mentioned by @coderimus should cover case if you want to have Magento src folder under the project directory. 
So, if it is the expected behaviour, we can close this issue. 
What do you think?

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @dmanners!

I am closing this issue as it seems that everything is working as expected.
If you want us to proceed with development here, please, reopen this issue and add as many details as you can.

Regards,
