### ISSUE TITLE
MFTF: `<stories>` gets recommendations from other objects

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2-phpstorm-plugin#255]
**Describe the bug** (*) 

![image](https://user-images.githubusercontent.com/1639941/82899537-7317c780-9f5b-11ea-8c09-3e8ead5581c0.png)
The `stories` node is for description of the test, this should not reference to any other object

**To Reproduce** (*) 

1. Turn on the MFTF support for the project
2. Create new test
3. Create `<stories` node and start filling the `value="`

**Expected behavior** (*) 

No autocomplete should appear

**Screenshots**

![image](https://user-images.githubusercontent.com/1639941/82899616-93e01d00-9f5b-11ea-8273-b97d262850d1.png)

**Please complete the following information:** (*) 

 - OS: Ubuntu 16.04
 - PhpStorm/Intellij version 2020.1
 - Version 1.0.0

**Additional context**

**Comment by drpayyne** [comment]
@magento I am working on this
