### ISSUE TITLE
It is possible to generate a PHP plugin for JS function

### ISSUE THREAD

**Issue by novikor** [magento/magento2-phpstorm-plugin#258]
**Describe the bug** (*) 

There is a `Create a Plugin...` option for not only PHP classes methods, but for JS as well which leads to Java exception as a result.
**To Reproduce** (*) 

1. Go to any JS file
2. Right-click on any JS function
3. Find `Create a Plugin...` option

**Expected behavior** (*) 

The functionality should be restricted for valid PHP classed only.

**Screenshots**
![image](https://user-images.githubusercontent.com/26086561/83518067-a5d53900-a4e2-11ea-8ecf-17f7c65631fd.png)

**Please complete the following information:** (*) 

 - OS: macOS Catalina 
 - PhpStorm 2020.1.1
 - Version 1.0.0

**Comment by VitaliyBoyko** [comment]
Hi @novikor 
The issue is well known and fixed in 1.0.1. Please update the plugin. Let me know if something goes wrong. Thanks!

**Comment by novikor** [comment]
Yep, now I see))
Thank you
