### ISSUE TITLE
Module version in module.xml is missing when creating new module

### ISSUE THREAD

**Issue by cap340** [magento/magento2-phpstorm-plugin#267]
**Describe the bug** (*) 

The required setup_version in module.xml is not added when a new module is created, and if you add it manually:  
`Provided module name "1.0.0" does not match expected "Vendor_Module"`

**To Reproduce** (*) 

1. Right click and select create new Magento module
2. Add module name Vendor/Module (or something else)
3. Add module version 1.0.0

**Expected behavior** (*) 

It seems strange to ask for module version on creation menu but not added in the created module.xml file.
As the module version is required I need to add it manually but the IDE return an error message :  
`Provided module name "1.0.0" does not match expected "Vendor_Module"`

Module is still 100% functional with this message

**Screenshots**

<img width="768" alt="1" src="https://user-images.githubusercontent.com/42498660/87236646-ef6f4880-c3eb-11ea-9df1-01b5d6940e37.png">
<img width="455" alt="2" src="https://user-images.githubusercontent.com/42498660/87236648-f302cf80-c3eb-11ea-98e9-265b3a2b3998.png">
<img width="1029" alt="3" src="https://user-images.githubusercontent.com/42498660/87236649-f39b6600-c3eb-11ea-9a0d-23ff2460699e.png">
<img width="1019" alt="4" src="https://user-images.githubusercontent.com/42498660/87236651-f39b6600-c3eb-11ea-9159-207346c0da43.png">
<img width="1017" alt="5" src="https://user-images.githubusercontent.com/42498660/87236653-f433fc80-c3eb-11ea-88ff-9506dda000a7.png">

**Please complete the following information:** (*) 

PhpStorm 2020.1.2
Build #PS-201.7846.90, built on June 3, 2020
Licensed to ......
Subscription is active until November 8, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true
Non-Bundled Plugins: CMD Support, com.alayouni.ansiHighlight, com.andrey4623.rainbowcsv, com.github.b3er.idea.plugins.arc.browser, com.intellij.ideolog, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.jade, ru.adelf.idea.dotenv, com.magento.idea.magento2plugin, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer

<img width="583" alt="Capture d’écran 2020-07-12 à 03 03 07" src="https://user-images.githubusercontent.com/42498660/87236714-e03cca80-c3ec-11ea-850b-42e6c3acd0be.png">
<img width="640" alt="Capture d’écran 2020-07-12 à 03 03 26" src="https://user-images.githubusercontent.com/42498660/87236716-e0d56100-c3ec-11ea-9615-276508ba2862.png">
<img width="402" alt="Capture d’écran 2020-07-12 à 03 04 02" src="https://user-images.githubusercontent.com/42498660/87236717-e16df780-c3ec-11ea-824e-69bd59b225a2.png">

**Comment by coderimus** [comment]
Hello @cap340 , 

The `Version` input handles the version of the module in composer.json of this module.
The parameter you have mentioned related to the setup version of the module, and it is optional. Please, check the XSD schema for the `module.xml` files. `lib/internal/Magento/Framework/Module/etc/module.xsd`

Please, report back to me if you have any questions.

**Comment by azmeehan** [comment]
Hi Guys, I've just came across this creating a new module today, wondering if theres any update on this one?

**Comment by horstmue** [comment]
Same here:
Provided module name "1.1.0" does not match expected "Vendor_Module"

**Comment by azmeehan** [comment]
@coderimus, can you elaborate on your original comment, Ive checked `/Magento/Framework/Module/etc/module.xsd` everything looks ok with schema's.  When checking the core module `Amz/Amazon-Pay-Module/etc/Module.xml `it seems ok.  Ie: phpStorm is satisfied with the values provided for `setup_version` within that core module.
