### ISSUE TITLE
Inspection for possible observer name duplication 

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#27]
We need to implement a check in a purpose to avoid accidentally overriding an observer.

**Acceptance criteria [case warnig]:**
Module_Module1 observer:
``` 
<event name="sales_order_save_before">
        <observer name="foo" instance="Bar"/>
    </event>
```
Module_Module2 observer:
``` 
<event name="sales_order_save_before">
        <observer name="foo" instance="Bar2"/>
    </event>
```

As a result, we need to show the warning like "The observer might override another observer. In case you do want to override the observer, please disable the original one and introduce the new one with the unique name".

**Comment by vasilii-b** [comment]
Hi @VitaliyBoyko,
May I work on this?
Thanks!
