### ISSUE TITLE
Change validation for Creating new observer dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#283]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.CreateAnObserverDialogValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
![image](https://user-images.githubusercontent.com/31848341/95055742-6458d280-06fc-11eb-83fa-612a705a7db3.png)

**Expected result (*)**
1. Creating new observer dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this
