### ISSUE TITLE
Add PHP form button block class code template description

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#287]
### Description (*)
Describe the purpose of the  PHP form button block class code template and containing variables. (Editor > File and Code templates)

![image](https://user-images.githubusercontent.com/20116393/95345460-691bb300-08c3-11eb-9465-e538bd76c892.png)

See the example here #50

**Comment by drpayyne** [comment]
@magento I am working on this
