### ISSUE TITLE
Add UI component form code template description

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#288]
### Description (*)
Describe the purpose of the UI component form code template and containing variables. (Editor > File and Code templates)

See the example here #50

![image](https://user-images.githubusercontent.com/20116393/95346398-7ab18a80-08c4-11eb-921b-c50c7b5aff83.png)

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by AndreyChorniy** [comment]
@VitaliyBoyko, Could you please check my PR for this issue? Let me know if you have any questions.
Thank you.
