### ISSUE TITLE
Add events.xml code template description

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#289]
### Description (*)
Describe the purpose of the events.xml code template and containing variables. (Editor > File and Code templates)
(Current description should be replaced ❗ )

See the example here #50

![image](https://user-images.githubusercontent.com/20116393/95346885-f8759600-08c4-11eb-8c7a-a0cda34b62f9.png)

**Comment by drpayyne** [comment]
@magento I am working on this
