### ISSUE TITLE
Inspection for using a block cacheable="false" attribute within default layout

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#29]
Utilizing `cacheable="false"` attribute within the default layout makes the whole site uncacheable. 
It's needed to warn the user about such an effect.

**Comment by konarshankar07** [comment]
Hello @VitaliyBoyko  
Can I work on this ticket?
Thanks

**Comment by VitaliyBoyko** [comment]
Sure.
