### ISSUE TITLE
Add routes.xml code template description

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#291]
### Description (*)
Describe the purpose of the routes.xml code template and containing variables. (Editor > File and Code templates)

See the example here #50

![image](https://user-images.githubusercontent.com/20116393/95347891-1bed1080-08c6-11eb-96f8-e0114055cd87.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
