### ISSUE TITLE
Change validation for the new plugin dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#293]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.CreateAPluginDialogValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.CreateAPluginDialog
![image](https://user-images.githubusercontent.com/31848341/95581427-b4f46680-0a41-11eb-92c3-b743989c8877.png)

**Expected result (*)**
1. Creating new plugin dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by coderimus** [comment]
Hello @drpayyne ,

We really appreciate your effort and enthusiasm but, please, keep assigning one issue on you which is currently in progress. This will allow others to join the contribution process.

Thank you,
Alex

**Comment by drpayyne** [comment]
Sure, @coderimus. Lemme fix that. Thanks.
