### ISSUE TITLE
Change validation for the injection of new ViewModel dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#294]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.InjectAViewModelDialogValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.InjectAViewModelDialog
![image](https://user-images.githubusercontent.com/31848341/95582108-d2760000-0a42-11eb-87d1-a1b947723cac.png)

**Expected result (*)**
1. Added validation for the new ViewModel injection dialogue with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this
