### ISSUE TITLE
Change validation for the new CLI command dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#296]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.NewCLICommandValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.NewCLICommandDialog
![image](https://user-images.githubusercontent.com/31848341/95583195-71e7c280-0a44-11eb-9c00-95b0a5f0accb.png)

**Expected result (*)**
1. Added new CLI command dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
@magento I am working on this
