### ISSUE TITLE
Change validation for the new controller dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#297]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.NewControllerValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.NewControllerDialog
![image](https://user-images.githubusercontent.com/31848341/95583467-d73bb380-0a44-11eb-865c-051c991ddc04.png)

**Expected result (*)**
1. Added new controller dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this
