### ISSUE TITLE
Change validation for the new cron group dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#298]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.NewCronGroupValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.NewCronGroupDialog
![image](https://user-images.githubusercontent.com/31848341/95583696-30a3e280-0a45-11eb-979d-448f81453719.png)

**Expected result (*)**
1. Added new cron group dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
@magento I am working on this
