### ISSUE TITLE
Completion. Remove PHP completions from all not appropriate places in XML files

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#30]
PHP classes and module names completion present in places where it completely unnecessary. 
Example (UI component name):
![image](https://user-images.githubusercontent.com/20116393/75878287-10ae9f80-5e22-11ea-8ff2-4feb37d92e94.png)

**Comment by konarshankar07** [comment]
Hello @VitaliyBoyko ..
Please assign this ticket to me. I'm working on this ticket
Thanks

**Comment by VitaliyBoyko** [comment]
Hi @konarshankar07 
Feel free to proceed.
