### ISSUE TITLE
Change validation for the new GraphQl resolver dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#300]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.NewGraphQlResolverValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.NewGraphQlResolverDialog
![image](https://user-images.githubusercontent.com/31848341/95584283-1fa7a100-0a46-11eb-80db-c94d8b17971a.png)

**Expected result (*)**
1. Added new GraphQl resolver dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this
