### ISSUE TITLE
Change validation for the new module dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#301]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.NewModuleDialogValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.NewModuleDialog
![image](https://user-images.githubusercontent.com/31848341/95584540-95137180-0a46-11eb-9799-fee6432e34b0.png)

**Expected result (*)**
1. Added new module dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this
