### ISSUE TITLE
Change validation for the overriding class by reference dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#303]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.OverrideClassByAPreferenceDialogValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.OverrideClassByAPreferenceDialog
![image](https://user-images.githubusercontent.com/31848341/95585496-fe47b480-0a47-11eb-8673-b4a7c3ae58aa.png)

**Expected result (*)**
1. Added overriding class by reference dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
@magento I am working on this
