### ISSUE TITLE
Change validation for the overriding in theme dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#304]
**TODO:**
1. We need to remove old validation from the dialogue (com.magento.idea.magento2plugin.actions.generation.dialog.validator.OverrideInThemeDialogValidator).
2. We need to add all validation rules from removed validator through annotations.

**Related Issue & PR as an example:**

- Issue: #302

- PR: #307

**The dialogue window we should change with new validation:**
com.magento.idea.magento2plugin.actions.generation.dialog.OverrideInThemeDialog
![image](https://user-images.githubusercontent.com/31848341/95585781-639ba580-0a48-11eb-8e02-a78076bc9104.png)

**Expected result (*)**
1. Added overriding in theme dialogue validation with annotations and it works as before (all previous validation rules are present)
2. Old validation removed from the code

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
@magento I am working on this
