### ISSUE TITLE
Add reference navigation and autocomplete for UI component

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#305]
**Is your feature request related to a problem? Please describe.**
Add completion and reference for UIComponent tag in layout XML files.
![image](https://user-images.githubusercontent.com/20116393/95586155-ef153680-0a48-11eb-96ca-8fcaa390f8d4.png)

**Comment by dylanngo95** [comment]
@magento I'm working on this.

**Comment by VitaliyBoyko** [comment]
Implemented in #354. 
Requires test coverage, issue is till open though.

**Comment by coderimus** [comment]
@VitaliyBoyko thank you for point this out. My bad, sorry.
@dylanngo95 can you assist us here and cover the autocomplete with tests?

**Comment by dylanngo95** [comment]
@coderimus Don't worry. I'll write a cover for it.
