### ISSUE TITLE
Add db_schema.xml generation with dialog window

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#309]
**TODO:**
1. We need to add db_schema.xml file generation
2. We need to add db_schema_whitelist.json file generation

**Expected result (*)**
1. It is possible to create new db_schema.xml file or edit an existing one.
2. It is possible to get actual db_schema_whitelist.json file after operations with db_schema.xml file.

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by VitaliyBoyko** [comment]
to be closed after whitelist.json implementation
