### ISSUE TITLE
Line markers. Fix performance warnings

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#31]
We have the following warning on the plugins and WEB API line markets:
![image](https://user-images.githubusercontent.com/20116393/75922032-e7fec800-5e6a-11ea-844d-720c86ed3462.png)

The issue could be fixed using `PsiTreeUtil.getDeepestFirst(psiElement)` or `PsiTreeUtil.getDeepestLast(psiElement)` function (`com.intellij.psi.util.PsiTreeUtil`).

**Comment by rogyar** [comment]
I will handle it

**Comment by rogyar** [comment]
Fortunately, we're not able to reproduce this issue. Please, feel free to close it.

**Comment by VitaliyBoyko** [comment]
@rogyar Thank you 🙏

**Comment by VitaliyBoyko** [comment]
It seems to be still reproducible. I will recheck it.
