### ISSUE TITLE
Add module names completion and reference in config.php

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#321]
**Is your feature request related to a problem? Please describe.**

Add the possibility to easily navigate from the config.php to a module.

**Describe the solution you'd like** (*)

Add completion and reference based on the existing ModuleNamesIndex.
Cover by tests.
Competition should work only for undeclared modules.

**Additional context**

![image](https://user-images.githubusercontent.com/20116393/96683822-57d2ac00-1383-11eb-8645-7ce4926ef323.png)

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
Draft branch is at https://github.com/magento/magento2-phpstorm-plugin/compare/2.1.0-develop...drpayyne:issue-321

**Comment by VitaliyBoyko** [comment]
Hi @drpayyne 

Please update your branch from the [issue-321](https://github.com/magento/magento2-phpstorm-plugin/tree/issue-321) branch. 
TY

**Comment by drpayyne** [comment]
Ah! I was trying to get `.withText("modules")` instead of `.withText(string().contains("modules"))` as you commited. I'll get that PR up and running. Thank you, @VitaliyBoyko!
