### ISSUE TITLE
Plugin linemarkers is missing for interface methods

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2-phpstorm-plugin#322]
**Describe the bug** (*) 

The system doesn't navigate from plugin to the subject method if a plugin has been created to an interface. There no special linemarker to navigate. However, if you create a plugin for the class the linemarker will be added and the system navigates successfully.
Take a look at the screenshots below.

**To Reproduce** (*) 

1. Create a plugin to interface
2. Go to created plugin method
3. Pay attention to the gutter icons panel

**Expected behavior** (*) 

The gutter icons panel has a linemarker with the hint "Navigate to target method" and the system has a possibility to navigate there.

**Screenshots**

Plugin has been created to the method of class
<img width="733" alt="plugin-to-class" src="https://user-images.githubusercontent.com/10788564/96698779-316a3c00-1396-11eb-8d64-df44b288659e.png">

Plugin has been created to the method of interface
<img width="987" alt="plugin-to-interface" src="https://user-images.githubusercontent.com/10788564/96698790-33cc9600-1396-11eb-8bf4-abb19b6fe880.png">

**Please complete the following information:** (*) 

 - OS: MacOS Catalina
 - PhpStorm/Intellij version 2020.2
 - Version 1.0.1

**Comment by drpayyne** [comment]
@magento I am working on this
