### ISSUE TITLE
Implement module name validation in 'Create a plugin' and 'New module' dialog

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2-phpstorm-plugin#332]
**Describe the bug**

To implement module existence validation for the field `Target Module` in the following scenarios
- Create a plugin dialog
- Create an observer dialog
- New module dialog

This was implemented in the old way and removed as part of https://github.com/magento/magento2-phpstorm-plugin/pull/324 and https://github.com/magento/magento2-phpstorm-plugin/pull/318, respectively, as its not directly possible using annotations. More info at https://github.com/magento/magento2-phpstorm-plugin/pull/324#discussion_r509635113.

**Expected behavior**

Target module field is validated using the list of indexed modules in the Magento 2 project

**Comment by drpayyne** [comment]
Closing with a better approach explained in comment: https://github.com/magento/magento2-phpstorm-plugin/pull/326#issuecomment-714742389

**Comment by VitaliyBoyko** [comment]
We can't use a simple Combobox for a modules list. It's inconvenient.

**Comment by drpayyne** [comment]
I understand @VitaliyBoyko, thanks. In that case, would it be better to create a new rule to validate `target module` fields? It would implement same logic of getting list of modules in current project and checking the existence of the value in the module list, but inside a rule so that annotations can be used and it can be reused.

**Comment by drpayyne** [comment]
I proposed yet another solution in https://github.com/magento/magento2-phpstorm-plugin/pull/339. Please check, @VitaliyBoyko.

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by drpayyne** [comment]
PR is merged (https://github.com/magento/magento2-phpstorm-plugin/pull/358), hence closing.
