### ISSUE TITLE
Change the validation of the Argument Name field in the ViewModel dialog window

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#369]
**Describe the bug**

Currently, we can't use an underscore `_` in the argument name, only letters and numbers. The underscore character is not prohibited for use in layouts by Magento, so it must be allowed for use in the dialog window.

**To Reproduce**

1. Open any layout file
2. Right click on the block
3. Select the **Inject a ViewModel...** option
4. Fill in all the input data and use the **view_model** value for the **Argument Name** field
5. Click **Ok** button

**Expected behavior**

The  View Model is added to the block with the specified name containing the underscore character.

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/97988824-9e49f100-1dee-11eb-91d4-2082dfa737f9.png)
![image](https://user-images.githubusercontent.com/1055999/97988835-a30ea500-1dee-11eb-944d-ae8807210450.png)

**Please complete the following information:**

 - OS: MacOS 10.15.7
 - PhpStorm/Intellij version: 2020.2.3
 - Plugin Version: 2.0.1

**Additional context**

Here are examples from the Magneto code where underscores are used:
- [magneto/module-theme/view/frontend/layout/default.xml](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/frontend/layout/default.xml#L43)
- [magneto/module-theme/view/frontend/layout/default.xml](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/frontend/layout/default.xml#L83)
- [magneto/module-cookie/view/frontend/layout/default.xml](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cookie/view/frontend/layout/default.xml#L14)
- [magneto/module-cookie/view/adminhtml/layout/default.xml](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cookie/view/adminhtml/layout/default.xml#L13)

**Comment by drpayyne** [comment]
@magento I am working on this
