### ISSUE TITLE
False positives when using path repositories

### ISSUE THREAD

**Issue by navarr** [magento/magento2-phpstorm-plugin#372]
**Describe the bug** (*) 

When using a path repository for development, you'll often have two directories containing the same code.  One in your path (and project), and one in the vendor directory.  When this happens, the plugin will flag false positives.

Here's an example:

![image](https://user-images.githubusercontent.com/145128/98255845-ddda1f80-1f4b-11eb-8c82-d7db743f0438.png)

(The file is `frontend/di.xml` for the named module)

**Please complete the following information:** (*) 

 - OS: macOS Catalina 10.15.7
 - PhpStorm/Intellij version: 2020.2.3
 - Plugin Version: 2.0.1

**Comment by VitaliyBoyko** [comment]
> you'll often have two directories containing the same code
Mark one of them as excluded
<img width="588" alt="Untitled 3" src="https://user-images.githubusercontent.com/20116393/111165251-7c842600-85a7-11eb-9ea1-98b78b251cd0.png">

**Comment by VitaliyBoyko** [comment]
Mark one directory as excluded
<img width="588" alt="Untitled 3" src="https://user-images.githubusercontent.com/20116393/111168355-ac80f880-85aa-11eb-8615-f8508e9043dd.png">

Just checked, works. But you may experience a little delay.
