### ISSUE TITLE
Line Marker. Navigation between original and override observers.

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#38]
Line Markers between original and overridden observers (with the same name and the same event).

**Comment by lbajsarowicz** [comment]
Could you explain more with some example?
I don't get the idea :-)

**Comment by VitaliyBoyko** [comment]
@lbajsarowicz 
For example:
You have some observer in the first module global area (First_Module/etc/events.xml).
```
  <event name="avesome_event">
        <observer name="foo" instance="Bar" />
    </event>
```
You replaces the implementation for the frontend in the second module (Second_Module/etc/frontend/events.xml).
```
  <event name="avesome_event">
        <observer name="foo" instance="Bar2" />
    </event>
```

The main idea is to visualize that the observer is overridden as it could be done by accident.

Also, I'm working on inspection duplicated names for the same area: #27. However, for different areas, an inspection is not an applicable option as an observer could be overridden intentionally as well and adding `Second_Module` to the `First_Module`  sequences is not required. Therefore, I think we can only visualize this via line markers.

**Comment by VitaliyBoyko** [comment]
And the case with the same area override using sequences should be covered by line markers as well.

**Comment by VitaliyBoyko** [comment]
Well, I've overthought this one once again. Using line marker here seems to be overhead. Override an observer using an observer name is not a good practice. It is better to show the error message.
