### ISSUE TITLE
Easier navigation through plugins

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#406]
**Is your feature request related to a problem? Please describe.**

At the moment, we can see the list of plugins for the method by clicking on the icon in the gutter. But if there are a lot of these plugins, the navigation between them is very confusing, because if we need to do something, we have to click on this icon many times, then select the desired plugin, set the breakpoint, then we need to go back to the main method and continue to perform this routine by selecting a plugin from the list. And since sometimes there are a lot of plugins, we can also miss some plugin. It also seems to me that the plugins are sorted in an unpredictable order.

![image](https://user-images.githubusercontent.com/1055999/100730397-0df5d080-33db-11eb-83aa-ddd9eb8bf78b.png)

![record](https://user-images.githubusercontent.com/1055999/100731367-5792eb00-33dc-11eb-9151-6e83cb0718bc.gif)

**Describe the solution you'd like** (*)

It would be very convenient if two new icons were added near to the plugin icon: the **previous** one and the **next** plugin. When we click on them, we would jump to the corresponding plugin according to the priority rules. Also, the main list of plugins should be sorted according to the rules specified here https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html#prioritizing-plugins

![image](https://user-images.githubusercontent.com/1055999/100731985-2e268f00-33dd-11eb-90cf-7cd42ed10b60.png)

I would also like you to add their type (**before**, **after**, or **around**) next to the list of plugins. This will help devs choose the right plugin faster. And if the same plugin class contains several different plugins, then each plugin must have a separate line.

![image](https://user-images.githubusercontent.com/1055999/100732479-cf154a00-33dd-11eb-829e-fc63386fbca2.png)

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by korovitskyi** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Hello, @korovitskyi!

Do we have any progress here?

Regards,

**Comment by bohdan-harniuk** [comment]
https://github.com/magento/magento2-phpstorm-plugin/pull/1121
