### ISSUE TITLE
Quick action to replace the dependency injection argument

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#409]
**Is your feature request related to a problem? Please describe.**

It seems to me that it would be convenient to implement the ability to quickly replace the injection argument. This will speed up the replacement of dependencies and reduce the amount of file creation routine di.xml, copying class names, and so on.

**Describe the solution you'd like** (*)

The most convenient place to add this quick action is to right-click on the constructor argument. After that, at the very bottom of the drop-down menu, you can add the item "Replace argument" (or something other). After that, a dialog box will appear with a suggestion to select the module in the context of which the di.xml will be created/modified and area selection, there should also be fields for entering the type and value of the replaced argument.

![image](https://user-images.githubusercontent.com/1055999/100768804-5a0d3900-340c-11eb-93bd-f6715fc51e45.png)

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by anzin** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Hello, @anzin!

Please, give me any update. Do we have something developed here? Do you have some blockers? 

Regards,

**Comment by anzin** [comment]
Hello, @bohdan-harniuk 

I have some progress on this task, but now there is no time to finish this, I can share my code if needed, for someone else to continue.

Thank you

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs!

I've developed this feature. 
You can see the result in the description to the PR.

Regards,
