### ISSUE TITLE
Additional option for "Copy Path..." action

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#414]
**Is your feature request related to a problem? Please describe.**

Now we have to copy the full path and then modify this value, and if we copy it from the vendor folder _vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml_, we need to open **composer.json** or **etc/module.xml** to find out the correct name of the module -> _Magento_Catalog::product/view/form.phtml_. With Magento modules, everything is simple, but third-party packages are often named differently from the module name.

**Describe the solution you'd like** (*)

In the context menu of the file (right click), there is an item **Copy Path...**. It would be very convenient if you add a quick copy of the **template**, **styles**, **script**, etc. paths to this item. So that the new item something like **Copy Module/Extension Path** immediately copies the value of the type **Vendor_Module::path/to/template.phtml**.

![image](https://user-images.githubusercontent.com/1055999/101455755-1b174000-3944-11eb-851c-163959c9f65e.png)

![image](https://user-images.githubusercontent.com/1055999/101455806-2bc7b600-3944-11eb-995b-c1ce903dc8ba.png)

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
@magento I am working on this
