### ISSUE TITLE
Change the validation of the Name field in the New Observer dialog window

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#421]
**Describe the bug** (*) 

Currently, we can't use a colon `:` in the observer name, only letter, numbers and underscore. The colon character is not prohibited for use in **events.xml** files by Magento, so it must be allowed for use in the dialog window.

**To Reproduce** (*) 

1. Open any class with event
2. Right click on the event
3. Select the **Create a new Observer for this event** option
4. Fill in all the input data and use the **Vendor_Module::Test** value for the **Name** field
5. Click **Ok** button

**Expected behavior** (*) 

The Observer is added to the event with the specified name containing the colon character.

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/102209873-7d42e880-3ee2-11eb-98c6-7f8f105951e0.png)

![image](https://user-images.githubusercontent.com/1055999/102209897-8469f680-3ee2-11eb-9555-fb8e36d6f8fc.png)

**Please complete the following information:** (*) 

 - OS: MacOS
 - PhpStorm: PhpStorm 2020.3 Build #PS-203.5981.175, built on December 2, 2020
 - Plugin Version: 3.0.1

**Additional context**

Similar issues with the validation of a parameter name:
- View model name validation https://github.com/magento/magento2-phpstorm-plugin/issues/369
- Plugin name validation https://github.com/magento/magento2-phpstorm-plugin/issues/422

**Comment by drpayyne** [comment]
@magento I am working on this
