### ISSUE TITLE
Change the validation of the Plugin Name field in the New Plugin dialog window

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#422]
**Describe the bug** (*) 

Currently, we can't use a colon `:` in the plugin name, only letter, numbers, dashes and underscore. The colon character is not prohibited for use in **di.xml** files for plugin name by Magento, so it must be allowed for use in the dialog window.

**To Reproduce** (*) 

1. Open any class
2. Right click on the method
3. Select the **Create a new Plugin for this method** option
4. Fill in all the input data and use the **Vendor_Module::Test** value for the **Plugin Name** field
5. Click **Ok** button

**Expected behavior** (*) 

The Plugin is added to the di with the specified name containing the colon character.

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/102210588-69e44d00-3ee3-11eb-8519-721f7fca1bf4.png)

![image](https://user-images.githubusercontent.com/1055999/102210603-6d77d400-3ee3-11eb-9bff-f06d18f1960d.png)

**Please complete the following information:** (*) 

 - OS: MacOS
 - PhpStorm: PhpStorm 2020.3 Build #PS-203.5981.175, built on December 2, 2020
 - Plugin Version: 3.0.1

**Additional context**

Similar issues with the validation of a parameter name:
- View model name validation https://github.com/magento/magento2-phpstorm-plugin/issues/369
- Observer name validation https://github.com/magento/magento2-phpstorm-plugin/issues/421

**Comment by drpayyne** [comment]
@magento I am working on this
