### ISSUE TITLE
Reference navigation for disabled observers

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#423]
**Is your feature request related to a problem? Please describe.**

Version 3.0.0 added [reference navigation for disabled plugins](https://github.com/magento/magento2-phpstorm-plugin/wiki/3.0.0-Release#disabled-plugins-in-dixml). It will be very useful to add the same behavior for observers.

Currently, when we press Ctrl+Click on the observer name, it shows us a notification **Cannot find declaration to go to**

![image](https://user-images.githubusercontent.com/1055999/102212153-cba5b680-3ee5-11eb-998c-a1a9e977dbce.png)

![image](https://user-images.githubusercontent.com/1055999/102212145-c0528b00-3ee5-11eb-87f6-2dbc4744d6ba.png)

**Describe the solution you'd like** (*)

Implement the same behavior for observers as for plugins.

**Additional context**

https://github.com/magento/magento2-phpstorm-plugin/issues/146
https://github.com/magento/magento2-phpstorm-plugin/pull/373

**Comment by drpayyne** [comment]
@magento I am working on this
