### ISSUE TITLE
Inspection warning when disabling a nonexistent observer in events.xml

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#424]
**Is your feature request related to a problem? Please describe.**

Version 3.0.0 [inspection warning](https://github.com/magento/magento2-phpstorm-plugin/wiki/3.0.0-Release#warning-when-disabling-a-nonexistent-plugin-in-dixml) when disabling a nonexistent plugin in di.xml. It will be very useful to add the same behavior for observers.

Currently, when we disabling the nonexistent observer, we don't see any inspection notifications

![image](https://user-images.githubusercontent.com/1055999/102212866-e9bfe680-3ee6-11eb-8932-71175076ab9e.png)

**Describe the solution you'd like** (*)

Implement the same inspection warning for observers as for plugins.

**Additional context**

https://github.com/magento/magento2-phpstorm-plugin/issues/147
https://github.com/magento/magento2-phpstorm-plugin/pull/382

**Comment by drpayyne** [comment]
@magento I am working on this
