### ISSUE TITLE
The added model and collection classes contain duplicate names of the imported classes

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#437]
**Describe the bug**

Add the model via the context menu on the module folder. After generating model classes, the generated code contains highlighted code sections. 

![image](https://user-images.githubusercontent.com/1055999/102759735-9685e200-4385-11eb-8751-1938f7af6761.png)

![image](https://user-images.githubusercontent.com/1055999/102759739-9a196900-4385-11eb-82dc-554a14807eb1.png)

**To Reproduce**

1. Right clink on model dir
2. Add new model
3. Fill form with values ![image](https://user-images.githubusercontent.com/1055999/102759527-4ad33880-4385-11eb-8854-e6fe39bf515b.png)
4. Click Ok
5. Open generated file and see highlighted errors

**Expected behavior**

The generated code does not contain highlighted code sections. You can import classes using aliases. 
For example:
```php
use Vendor\Module\Model\ResourceModel\Test as ResourceModel;
use Vendor\Module\Model\Test as DataModel;
```

**Please complete the following information:** 

 - OS: MacOS
 - PhpStorm: PhpStorm 2020.3 Build #PS-203.5981.175, built on December 2, 2020
 - Plugin Version: 3.0.2

**Comment by drpayyne** [comment]
@magento I am working on this
