### ISSUE TITLE
Templates. Fill information about Plugin Templates

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#44]
Fill the information about the following templates to apropriate description files, see `resources/fileTemplates/code/` on the branch `1.0.0-develop`:
* `resources/fileTemplates/code/Magento Plugin After Method.php.ft`
* `resources/fileTemplates/code/Magento Plugin Around Method.php.ft`
* `resources/fileTemplates/code/Magento Plugin Before Method.php.ft`

Information about plugins see here https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html

Check the result under Editor > File and Code Templates
Example:
![image](https://user-images.githubusercontent.com/20116393/77056636-5bf8ae80-69db-11ea-97c2-a91e790f7e91.png)

**Comment by konarshankar07** [comment]
Hello @VitaliyBoyko ....
Can I work on this ticket?
Thanks

**Comment by VitaliyBoyko** [comment]
Sure

**Comment by konarshankar07** [comment]
@VitaliyBoyko .... Thanks :)
