### ISSUE TITLE
Overriding the interface generates invalid php code

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#443]
**Describe the bug**

When I try to override the interface with a new preference, it results in the wrong php code being generated. It generates a `class` instead of `interface`. The context menu also contains a `Override this class by a new Preference` option, and it seems to me that it can be changed to `Override this interface by a new Preference`. So we will have `Override this class by a new Preference` option for overriding classes and `Override this interface by a new Preference` option for overriding interfaces.

**To Reproduce**

1. Go to `vendor/module/Api/*` folder
2. Right-click on any interface 
3. Choose `Override this class by a new Preference`
4. Fill the form
5. Click `Ok` button
6. Check the generated php file

**Expected behavior**

1. The generated file contains a valid interface
2. The context menu options reflect the related option names:
    - `Override this interface by a new Preference` for interfaces
    - `Override this class by a new Preference` for classes

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/103132332-378dd900-46b5-11eb-8c5b-f03ba504e4c7.png)

![image](https://user-images.githubusercontent.com/1055999/103132341-3e1c5080-46b5-11eb-8542-08b7bbdaadd2.png)

![image](https://user-images.githubusercontent.com/1055999/103132352-45435e80-46b5-11eb-922b-efb74e4c117c.png)

**Please complete the following information:**

 - OS: MacOS
 - PhpStorm version: 2020.3
 - Plugin Version: 3.0.3

**Comment by drpayyne** [comment]
@magento I am working on this
