### ISSUE TITLE
Overriding the layout file does not work correctly

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#444]
**Describe the bug**

When I try to override a layout file, the plugin places the new file in the wrong `app/design/frontend/Vendor/theme/Vendor_Module/layout/route_controller_action.xml` path. But layouts have two or even three different approaches to overriding. This can be found in this [article](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-override.html).
We can **override** or **extend** the layout file. The current behavior is called an **extending**, since the new file is located directly in the `app/design/frontend/Vendor/theme/Vendor_Module/layout/` folder, which means that all layouts collected by fallback will be merged into one common layout file. To override this file, it must be located in the `app/design/frontend/Vendor/theme/Vendor_Module/layout/override/base/` folder. But that's not all. Overriding also has two different ways: we can override the **module layout file** and the **theme layout file**. Both of these methods should place the new files in different locations. Moreover, when we overriding a theme layout file, we can only place the overridden file in child themes only.

**To Reproduce**

1. Go to any layouts folder
2. Right-click on any layout file
3. Choose `Override this template in a project theme` option
4. Check the **overridden** file path.

**Expected behavior**

When right-clicking on the layout file, we should have two options:
1. `Extend this layout in a project theme`
2. `Override this layout in a project theme`

When you select the first option, the behavior should work as it does now. This option will create a new file directly in the `app/design/frontend/Vendor/theme/Vendor_Module/layout/` folder. Only the name of the option will change here.

When we select the second option, the behavior should be different depending on the selected layout file. 
- If we try to override the **module layout file**
    - then the theme selection window should offer all the themes available in the `app/design/frontend/` folder.
    - the new file should be located in the folder `app/design/frontend/Vendor/theme/Vendor_Module/layout/override/base/`
- If we try to override the **theme layout file**
    - then the theme selection window should offer only offer child themes that have an overridable theme in their parents, available in the `app/design/frontend/` folder
    - the new file should be located in the folder `app/design/frontend/Vendor/theme/Vendor_Module/layout/override/theme/Parent_Vendor/parent_theme/`

You might also want to rename the menu item so that when you select a layout file, it is called `Override this *layout* in a project theme` instead of `Override this *template* in a project theme`

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/103133442-8b9bbc00-46bb-11eb-8877-72990e828326.png)

![image](https://user-images.githubusercontent.com/1055999/103133443-8fc7d980-46bb-11eb-936a-43b50771beb7.png)

![image](https://user-images.githubusercontent.com/1055999/103133445-922a3380-46bb-11eb-8b37-ec6b162d04a2.png)

![image](https://user-images.githubusercontent.com/1055999/103133446-948c8d80-46bb-11eb-8659-2b95df9d60e2.png)

**Please complete the following information:**

 - OS: MacOS
 - PhpStorm version: 2020.3
 - Plugin Version: 3.0.3

**Comment by dylanngo95** [comment]
I still working on this.
