### ISSUE TITLE
It is possible to create a plugin for a class that implements NoninterceptableInterface

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#445]
**Describe the bug**

Magento provides [\Magento\Framework\ObjectManager\NoninterceptableInterface](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/ObjectManager/NoninterceptableInterface.php). If a class implements this interface, code generation does not create **Interceptor** for these classes, which means that plugins for these classes will not work. But PhpStorm Plugin allows us to create Magento Plugins for such classes.

**To Reproduce**

1. Open any class that implements `\Magento\Framework\ObjectManager\NoninterceptableInterface`
2. Right-click on any method
3. Choose `Create a new Plugin for this method`
4. Fill the form
5. Click `Ok` button
6. Check the generated plugin class

**Expected behavior**

The `Create a new Plugin for this method` option is disabled (inactive) for such classes. Perhaps you should add some information about why this action is not available. If this option is removed without explanation, it may discourage developers.

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/103135276-3c0fbd00-46c8-11eb-9ade-5e81044fde7a.png)

![image](https://user-images.githubusercontent.com/1055999/103135295-5c3f7c00-46c8-11eb-8e56-784f2251f06e.png)

**Please complete the following information:**

 - OS: MacOS
 - PhpStorm version: 2020.3
 - Plugin Version: 3.0.3

**Comment by VitaliyBoyko** [comment]
Good catch @DmitryFurs 
Thank you 🙏
