### ISSUE TITLE
Reference. MFTF 'extended by' reference.

### ISSUE THREAD

**Issue by sergiy-v** [magento/magento2-phpstorm-plugin#452]
It will be nice to have 'extended by' reference for MFTF tests.

Example.
It's possible to navigate to extended test (AdvanceCatalogSearchSimpleProductByPriceTest) by clicking on it, see example below.
```
<test name="AdvanceCatalogSearchBundleByPriceTest" extends="AdvanceCatalogSearchSimpleProductByPriceTest">
```

But there is no way to go back (back reference), it will be good to have 'extended by' reference list (by clicking on test name AdvanceCatalogSearchSimpleProductByPriceTest), see example below.
```
<test name="AdvanceCatalogSearchSimpleProductByPriceTest">
```

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this
