### ISSUE TITLE
the plugin won't update correctly with the new jetbrains idea update dialog

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2-phpstorm-plugin#454]
**Describe the bug** (*) 

While opening intellij idea I get a message that the plugin needs to be update 

![image](https://user-images.githubusercontent.com/20220341/104740213-59c4c500-5750-11eb-80ae-27586279b30a.png)

I click on update button and try to restart the ide

![image](https://user-images.githubusercontent.com/20220341/104740276-6e08c200-5750-11eb-9b6c-5edd20e9c188.png)

On restarting the IDE it mentions the plugin needs to be updated. 

![image](https://user-images.githubusercontent.com/20220341/104740561-c4760080-5750-11eb-978e-8733c5dc55fb.png)

**To Reproduce** (*) 

I've shown in the images above the sequence. 

**Expected behavior** (*) 

The plugin is updated correctly.

**Screenshots**

**Please complete the following information:** (*) 

 - OS: Windows 10 x64
 - Intellij IDEA 2020.3.1
 - Plugin Version: 3.0.3

**Additional context**

**Comment by danslo** [comment]
Can +1 on this. Workaround is to uninstall manually and then install again.

**Comment by VitaliyBoyko** [comment]
I've provided an update in 3.1.3. However its kinda triage not 100% working for sure solution so I'd like to ask you check whether update works for you after release. The release will be published soon.

**Comment by VitaliyBoyko** [comment]
Hi @danslo @ioweb-gr 

Is the issue still reproducible with 3.1.3?

**Comment by danslo** [comment]
Upgrade worked correctly for me.
