### ISSUE TITLE
Inspection for possible plugin duplication

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#48]
We need to implement a check in a purpose to avoid accidentally overriding a plugin.

Create 2 modules with di.xml files.
Module_Module1 di.xml:
```
<type name="Target">
        <plugin name="plugin_name" type="Module\Module1\Plugin" />
</type>
```
Module_Module2 di.xml:
```
<type name="Target">
        <plugin name="plugin_name" type="Module\Module2\Plugin" />
</type>
```
As a result, we need to show the warning like "The plugin might override another plugin. In case you do want to override the plugin, please disable the original one and introduce the new one with the unique name".

**Comment by vasilii-b** [comment]
Hi @VitaliyBoyko,
Can I work on this one, please?

**Comment by VitaliyBoyko** [comment]
@vasilii-b You can self-assign issues :) Please give a try ;)

**Comment by VitaliyBoyko** [comment]
Hi @vasilii-b 
Would you like to cover it by a test?
Thank you!

**Comment by vasilii-b** [comment]
Hi @VitaliyBoyko,
Yeah, that would be nice! :)
