### ISSUE TITLE
Backport: Plugin does not work on 2019.1.4

### ISSUE THREAD

**Issue by devamitbera** [magento/magento2-phpstorm-plugin#494]
**Describe the bug** (*) 

The latest plugin does not work on the 2019.1.4 fallback version

**To Reproduce** (*) 

Installed plugin 

Goto Setting>Language & Framework >PHP> Languages,
And  Cannot see  Magento at Langauge List

**Expected behavior** (*) 

Goto Setting>Language & Framework >PHP> Languages,
And    Magento should  show  at Langauge List

**Screenshots**

![imageedit_0_2119190354](https://user-images.githubusercontent.com/6008488/108412382-cf401b80-724f-11eb-84ee-535c86971894.jpg)

**Please complete the following information:** (*) 

 - OS: Ubuntu 18
 - PhpStorm/Intellij version: [2019.1.4]
 - Plugin Version

**Comment by bohdan-harniuk** [comment]
Hello, @devamitbera!

Please, make sure that your PHPStorm version is supported by the desired plugin version: https://plugins.jetbrains.com/plugin/8024-magento-phpstorm

If everything is satisfied for your case, please, reopen this issue and the desired plugin version in the comment.

Regards,
