### ISSUE TITLE
JetBrains links to dkvashninbay/magento2plugin

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2-phpstorm-plugin#5]
It appears this was created under dkvashninbay/magento2plugin and then moved under the magento organization. JetBrains is still showing the original author of the plugin and not this one.

**Comment by nntoan** [comment]
Magento 2 team forked from it. And this repo is still under development.

**Comment by davidbrandastic** [comment]
@nntoan @voleye any timeline on this becoming the primary repo and an update being released?

**Comment by voleye** [comment]
@davidbrandastic There are few more improvements for autocompletion have been planned to make it more intelligent. ETA ~ the end of current week, Then, probably some time for review, testing, I do believe it can be released in 2-3 weeks

**Comment by danmooney2** [comment]
Fixed in https://github.com/magento/magento2-phpstorm-plugin/pull/4.  This is the primary repo now.
