### ISSUE TITLE
Invalid check for "setup_version" (ModuleDeclarationInModuleXmlInspection)

### ISSUE THREAD

**Issue by mvenghaus** [magento/magento2-phpstorm-plugin#500]
**Describe the bug** (*) 

In the module.xml the "setup_version" attribute is always wrong.

`Provided module name "1.0.0" does not match expected "Vendor_Module"`

It seems that the "setup_version" attribute is checked against the name but should be ignored.

**To Reproduce** (*) 

1. create module.xml with setup_version attribute

**Expected behavior** (*) 

No Error

**Please complete the following information:** (*) 

- Magento 2.4.2

**Additional context**

**Comment by anzin** [comment]
@magento I am working on this
