### ISSUE TITLE
Implement table stop editing for specified dialogs

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#528]
When editing a cell in a JTable the table doesn’t know when a user is finished editing the cell. Therefore it is the user's responsibility to tell the table when to stop editing. 

For now, almost all tables in our dialog windows have the next problem: if you edit table cell and click on the OK button without clicking previously on another table cell or JComponent, the value won't be saved to the table model and generation won't know about it.

We should fix that for all already created dialog windows with tables that have such issue:

1. Magento 2 UI Component Form generation
2. Magento 2 Data Mode generation
3. Magento 2 Declarative Schema XML generation

<img width="1002" alt="Screenshot 2021-04-08 at 17 15 16" src="https://user-images.githubusercontent.com/31848341/114042399-1335c100-988e-11eb-8484-f880b178730c.png">
<img width="505" alt="Screenshot 2021-04-08 at 17 14 19" src="https://user-images.githubusercontent.com/31848341/114042407-14ff8480-988e-11eb-8ea0-833d97746bbd.png">
<img width="848" alt="Screenshot 2021-04-08 at 17 12 45" src="https://user-images.githubusercontent.com/31848341/114042411-15981b00-988e-11eb-95b9-2da51289fd2c.png">

**Describe the solution you'd like** (*)

To fix that add the next code to an action listener method:
`
if (tableName.isEditing()) {
        tableName.getCellEditor().stopCellEditing();
}
`
Replace tableName with the actual table name. If there are few tables, duplicate it.

**Comment by anzin** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Hello! It was implemented in this PR: https://github.com/magento/magento2-phpstorm-plugin/pull/544

So, this issue can be closed.
