### ISSUE TITLE
Project Template. Add project template for Magento Module

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#53]
Action New Module MVP was added in #39.

We need to add the Magento Module project template using the based on #39 templates.
Functionality should be similar to the WordPress module project template.

![image](https://user-images.githubusercontent.com/20116393/77467049-e5f9aa80-6e13-11ea-9f01-abdefdc527ff.png)

![image](https://user-images.githubusercontent.com/20116393/77467149-2527fb80-6e14-11ea-9f47-9c4e6309a0e8.png)

**Comment by roma-glushko** [comment]
Hey @VitaliyBoyko, can you please assign this one to me? 🙏

**Comment by VitaliyBoyko** [comment]
@roma-glushko 
I will cover this one. ;)
