### ISSUE TITLE
Feature: Report Exception Button

### ISSUE THREAD

**Issue by lfluvisotto** [magento/magento2-phpstorm-plugin#543]
**Is your feature request related to a problem? Please describe.**

#542 

**Describe the solution you'd like** (*)

An exception happened, then I would like to be able to "report exception" to here as an issue, just clicking on button "report exception"

**Describe alternatives you've considered**

Copy and paste the exception and create manually the issue here.

**Additional context**

![image](https://user-images.githubusercontent.com/535626/114602407-f2de7b80-9c6c-11eb-9db0-7c7e2b500748.png)

**Comment by bohdan-harniuk** [comment]
@magento I am working on this
