### ISSUE TITLE
Action/Code Generation. Add license select to the new module

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#55]
Action New Module MVP was added in #39.

We need to implement a license select for the new module action.
Select should have the following options:
* Open Software License (OSL)
* Mozilla Public License (MPL)
* Massachusetts Institute of Technology License (MITL)
* GNU Lesser General Public License (LGPL)
* GNU General Public License (GPL)
* Berkeley Software Distribution License (BSDL)
* Apache Software License (ASL)
* Academic Free License (AFL)

The selected license should be automatically added to the composer JSON. 

![image](https://user-images.githubusercontent.com/20116393/77467956-8dc3a800-6e15-11ea-98ed-64a2dbecc015.png)
![image](https://user-images.githubusercontent.com/20116393/77468040-acc23a00-6e15-11ea-8811-8193f48d083f.png)

**Comment by vasilii-b** [comment]
Hey @VitaliyBoyko,
Can I work on this?
