### ISSUE TITLE
Develop preference xml inspections

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#566]
We should have preference XML attributes inspections:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Foo\Bar\Api\Data\FooAInterface" type="Foo\Bar\Model\Data\FooB"/>
</config>
```

For example, above we have two declared classes:

1. Foo\Bar\Api\Data\FooAInterface
2. Foo\Bar\Model\Data\FooB

What if the **Foo\Bar\Api\Data\FooAInterface** is a typo?
What if the **Foo\Bar\Model\Data\FooBe** is a typo too?

We need to cover this inspection to show if any of these classes don't exist.

**Comment by Iamwade** [comment]
@magento I am working on this
