### ISSUE TITLE
Develop plugin declaration types inspections

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#579]
We should have plugin declaration types inspections:

```
<type name="Foo\Bar\Block\Order\TestA">
        <plugin name="foo_bar_do_smth_with_test_a" type="Foo\Bar2\Plugin\Block\Order\TestAPlugin"/>
</type>
```

For example, above we have the declared classes:

1. Foo\Bar\Block\Order\TestA
2. Foo\Bar2\Plugin\Block\Order\TestAPlugin

What if some of them have a typo?
We need to cover this inspection to show if any of these classes don't exist.

**Comment by Iamwade** [comment]
@magento I am working on this
