### ISSUE TITLE
Action/Code Generation. Block generation

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#58]
Add action and templates for generating blocks.

* Right-click on the module Block directory
* Create a block action is accessible
* Click on the action
* Create a block dialog is shown
* Dialog contains (select `Block Type` [admin, storefront], text input `Parent Directory`, text input `Block Name`, Ok button, Cancel Button)
* Block created within the Parent Directory after filling out required fields and click the Ok button

**Comment by roma-glushko** [comment]
@VitaliyBoyko can you please assign this one to me?

**Comment by roma-glushko** [comment]
So far, the progress here is the following:

1. Added a new generation action:

![2020-04-03_17-36-17](https://user-images.githubusercontent.com/9402690/78372327-cf044680-75d1-11ea-95da-57be0f9d5917.png)

2. The action opens a new block generation wizard:

![2020-04-03_17-36-38](https://user-images.githubusercontent.com/9402690/78372373-dfb4bc80-75d1-11ea-99bb-a16be7e2701a.png)

Remaining stuff:

1. Shows the action item only when you click on the module directory 
2. Add block generation logic like it was done for plugin components
