### ISSUE TITLE
Create new plugin in vendor folder

### ISSUE THREAD

**Issue by mvenghaus** [magento/magento2-phpstorm-plugin#584]
When I'm developing a module in the vendor folder I can't use your option for creating a new plugin. The modules are not shown in the list.

**Describe the solution you'd like** (*)

Collect additional modules from vendor where directory is set as "Sources Root" and a namespace is defined.

Regards
Marcus

**Comment by VitaliyBoyko** [comment]
Hi @mvenghaus 

In this case, you supposed to have this module opened as a separate project (as, most likely, it has its own Git repo). Magento should be added via the `include path` feature.

<img width="786" alt="Screenshot 2021-05-03 at 10 33 39" src="https://user-images.githubusercontent.com/20116393/116851609-59ffa800-abfb-11eb-955c-7ad9c736c50c.png">

This is a correct way to develop modules, I believe. The vendor dir should remain untouchable :)

**Comment by mvenghaus** [comment]
Hi @VitaliyBoyko,

I can see your point. But how do you enable your module in the magento installation to test it?

But I think it's not the way most developers work and that for good reason. If you develop one single module I think your solution works great. But if you work on a whole project you often switch between modules. If you work in vendor it's like working in app/code with full support.
- git support if you add vendor module source root to version control
- full phpstorm features if you mark the directory as source root and add a namespace
- always direct access to all your modules especially when you have a lot of them (> 20) .. without having 20 projects open

What do you think?

Regards
Marcus

**Comment by VitaliyBoyko** [comment]
Thanks, @mvenghaus for clarification 
 
>  But how do you enable your module in the magento installation to test it?
I think a symlink may help here. I tried this for a single module and it worked like a charm. I think the amount of modules is not important, you can link the whole vendor.

 > full phpstorm features if you mark the directory as source root and add a namespace
 I really doubt whether we need to implement this as it contradicts with initial idea of the composer packages directory. Marking the directory as source root sounds like a dirty hack, I'd rather add some explicit config. Moreover, it is considered by IDE as a sources root by default. 
I highly recommend using a symlink anyway. Let me know if it works for your case. 

Best
Vitalii

**Comment by DmitryFurs** [comment]
@VitaliyBoyko @mvenghaus It is also possible to attach several other modules to the current one, and develop all the necessary repositories in one window
![image](https://user-images.githubusercontent.com/1055999/116974690-2722e600-acc7-11eb-8bde-fa87618844cb.png)
![image](https://user-images.githubusercontent.com/1055999/116974729-35710200-acc7-11eb-8879-420770e3448d.png)
