### ISSUE TITLE
Existing modules aren't recognized for editing.

### ISSUE THREAD

**Issue by tschallacka** [magento/magento2-phpstorm-plugin#589]
I have sometimes existing Magento modules I need to modify, in which I'd like to be able to use this plugin, but currently it only shows "create new module"

![menu only shows new meu](https://user-images.githubusercontent.com/8638425/117429974-e249ba00-af27-11eb-886f-d0aa9ef3d65f.png)

When I right click on a module that has been generated by the plugin, I get other options

![shows create options](https://user-images.githubusercontent.com/8638425/117430183-28068280-af28-11eb-961b-1a76e153f8cb.png)

I've tried looking through all the files in .idea and ~/.config and ~/.cache but I found nowhere a reference where this plugins stores what qualifies as a module so I could hack it in manually.

**Describe the solution you'd like** (*)

An option: Mark directory as Magento module, either via  the mark directory module as menu, or via another option/setting in options settings.

**Describe alternatives you've considered**

An xml config/pointer to a file/setting you can edit to mark the directory as a magento module for the magento plugin.

**Comment by tschallacka** [comment]
I found the fix why my modules weren't recognized. I used a constant for the module name in registration.php. The regex test for module name failed on the constant of course.

Maybe focus your regex test on the module.xml instead of the registration.php?

Would that classify this as as a bug?

**Comment by bohdan-harniuk** [comment]
Hello, @tschallacka!

No, we cannot classify this issue as a bug.
The generated content meets the requirements.
I am closing this issue.

Thanks, Bohdan
