### ISSUE TITLE
Not possible to override the js/css files from the lib/web/* folder

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#603]
**Describe the bug**

Sometimes there is a need to override the **js**/**css** file from the main **/lib/web/*** folder. The plugin does not support this action and does not display its own item in the context menu for files from this folder.

**To Reproduce**

1. Go to **/lib/web/***
2. Right Click on any js file
3. See that **Override this file in a project theme** item is missing in contect menu.

**Expected behavior**

Files from the **/lib/web/*** folder are available for quick overriding in the theme.

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/121731963-43057d00-cafa-11eb-8397-f4a9567be3d6.png)

**Please complete the following information:**

- OS: MacOS 11.4
- PhpStorm version: 2021.1.3
- Plugin Version: 3.2.2

**Comment by bohdan-harniuk** [comment]
It is not a bug. It is feature request.

**Comment by SilinMykola** [comment]
@magento I am working on this
