### ISSUE TITLE
Overriding layouts and templates allows to select an incompatible theme

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#604]
**Describe the bug**

If you try to overwrite the layout / template and so on, all the available themes are available in the dropdown. But this makes it possible to make an error and when overriding a file from the **frontend** folder, you can accidentally select the **backend** theme.

![image](https://user-images.githubusercontent.com/1055999/121732073-6fb99480-cafa-11eb-9ebc-600cd9255582.png)

**To Reproduce**

1. Go to frontend/layout folder in any module.
2. Right Click on any xml file.
3. Choose **Override this template in a project theme**.
4. Select adminhtml theme.
5. Create and verify a new file.

**Expected behavior**

When calling the override dialog from the **frontend** folder, only the **frontend** themes should be listed, when calling the rewrite dialog from the **adminhtml** folder, only the **adminhtml** themes should be available. When calling the rewrite dialog from the **base** folder, all the themes should be available.

**Please complete the following information:**

- OS: MacOS 11.4
- PhpStorm version: 2021.1.3
- Plugin Version: 3.2.2

**Comment by Iamwade** [comment]
@magento I am working on this
