### ISSUE TITLE
The content of the generated plugin class has problems

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#605]
**Describe the bug**

All three types of generated plugins have problems in the resulting content. Especially many problems are encountered if the pluginised method has input arguments. All plugin types do not use the short name of the imported Subject class. Also, in all plugins, there is an empty line for before the first method. In the **after** plugin the problem in the generated php doc, some arguments use FQCN, some are short name, some argumets have incorrect names, some arguments are duplicated.

**To Reproduce** (*)

1. Create all three types of plugins with a quick action
2. Check the resulting content

**Expected behavior**

The resulting content is valid and does not require any changes from the developer.

**Screenshots**

![image](https://user-images.githubusercontent.com/1055999/121732173-95469e00-cafa-11eb-974d-68edae41a7b2.png)

Before plugin
![image](https://user-images.githubusercontent.com/1055999/121732186-9aa3e880-cafa-11eb-8246-f03f11a26008.png)

After plugin
![image](https://user-images.githubusercontent.com/1055999/121732197-9ed00600-cafa-11eb-8220-95a9ac66bea6.png)

Around plugin
![image](https://user-images.githubusercontent.com/1055999/121732208-a394ba00-cafa-11eb-8e9c-36000564d635.png)

**Please complete the following information:**

- OS: MacOS 11.4
- PhpStorm version: 2021.1.3
- Plugin Version: 3.2.2

**Comment by bohdan-harniuk** [comment]
@magento I am working on this
