### ISSUE TITLE
Create new Module context menu disappears randomly

### ISSUE THREAD

**Issue by ProxiBlue** [magento/magento2-phpstorm-plugin#611]
**Describe the bug** (*) 

With the plugin installed, and a magento 2 project open, the Create New Module context menu is missing

**To Reproduce** (*) 

Install module, open a magento 2 project, right click on app/code folder.
Context menu is missing

**Expected behavior** (*) 

Create New Module menu option should be listed

**Screenshots**

![image](https://user-images.githubusercontent.com/4994260/123274249-efe9ec00-d535-11eb-960a-215dbe3fa4c2.png)

![image](https://user-images.githubusercontent.com/4994260/123274319-fe380800-d535-11eb-8fe1-cb24d3eaa72f.png)

**Please complete the following information:** (*) 

 - OS: 
 21:51 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
 - PhpStorm/Intellij version:2021.1.3
 - Plugin Version: 3.2.2

**Comment by eduard13** [comment]
Hi @ProxiBlue, thank you for reporting this issue, could you please make sure the Magento integration is enabled in `PHP / Frameworks`?
![image](https://user-images.githubusercontent.com/15868188/123951213-3bc0e900-d9ad-11eb-9870-cfbece188bdc.png)

Could you please additionally add if any other features (Plugin, M2 module) are available and only `New Module` context menu is missing?

Thank you.

**Comment by ProxiBlue** [comment]
Hello,

Yes it is.

![image](https://user-images.githubusercontent.com/4994260/123995774-3d1c0100-da01-11eb-89a2-a63ebe16b37e.png)

I noticed that when I use New project, the option is listed:

![image](https://user-images.githubusercontent.com/4994260/123995911-5d4bc000-da01-11eb-9e42-37e1b3c782ae.png)

For some reason, when withing a magento 2 project, the context is not working, so its not detecting that my root of th3 project is magento 2.

However, I may have figured it out:

The setting for 'sources root' was not set on the root of the the project source code. Since I had done that, I am finding the context menu appearing :)
That said, It has happened before that it works for a bit, then suddenly the option drops out again. I will update ticket again if that happens, but for now, seems to be working fine again.

**Comment by bohdan-harniuk** [comment]
Hello, @ProxiBlue!
Thank you, for your report!

Be sure that source root (Magento installation path) is set for each new project.
Everything should be fine if it is.

For now I am closing this issue as everything is fine for you.
If you will detect suspicious behaviour regarding this, please, report this to us.

Thanks,
Bohdan
