### ISSUE TITLE
Jump to code in mixins

### ISSUE THREAD

**Issue by tschallacka** [magento/magento2-phpstorm-plugin#614]
**Is your feature request related to a problem? Please describe.**

When editing a mixin, it's frustrating not to be able to jump to code which is referenced within the require-config.js like it's possible within the layout xml files.

```javascript
var config = {
    config: {
        mixins: {
            'Magento_Checkout/js/view/shipping': {
                'MyPlugin_Checkout/js/Magento_Checkout/view/shipping-mixin': true
            },
```

**Describe the solution you'd like** (*)

When hitting F4 or CTRL + click on a line like `'MyPlugin_Checkout/js/Magento_Checkout/view/shipping-mixin'` it would be ideal that the plugin would try to locate the the Plugin folder for MyPlugin, then go to the relative folder for frontend or adminhtml when the web folder then open the relative `js/Magento_Checkout/view/shipping-mixin.js` file. 
If it can't be found in app/code it will check the vendor folder for the given plugin.

The same should occur for the parent module mixin that is referenced `'Magento_Checkout/js/view/shipping'` so it becomes easy to jump from one to the other.

**Describe alternatives you've considered**

Javascript phpdoc automatic annotiation to make a @link to the given file when needed.

**Comment by bohdan-harniuk** [comment]
Hello, @tschallacka !

Thank you for your idea!
We'll try to implement this feature.

Regards,

**Comment by doninAtwix** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
Hi @bohdan-harniuk.
Checked functionality and when we clicked CTRL + click on parent module script we have search result where is the script mentioned.
See screenshot
<img width="1310" alt="Screenshot 2022-02-01 at 15 11 06" src="https://user-images.githubusercontent.com/89141549/151977656-680d8623-f7c8-41c2-97c4-be199cc2edda.png">

Thank you.

**Comment by bohdan-harniuk** [comment]
Hello, @VitaliyBoyko!

Could you please help us here?

The `com.magento.idea.magento2plugin.reference.provider.FilePathReferenceProvider` file is responsible for such completions. This class has over complicated logic and can have negative impact on the performance.

At first, we should think about how to change this implementation to not break existing functional.
The next one, we should rewrite this part:

<img width="972" alt="Screenshot 2022-02-15 at 16 41 43" src="https://user-images.githubusercontent.com/31848341/154084658-877478a6-719c-4d5b-8109-cc1e5c5b117b.png">

In the current implementation it is not providing references to the requested paths (mixin target + mixin file).

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @tschallacka!

We've fixed this issue. It will be delivered in the upcoming release: 4.3.0.

Regards,

**Comment by tschallacka** [comment]
Nice! Thanks!
