### ISSUE TITLE
Exclude Tests from search

### ISSUE THREAD

**Issue by cjnewbs** [magento/magento2-phpstorm-plugin#620]
When searching for class consts or strings, function calls etc, I find it frustrating to have all the Magento tests show up as normally I am trying to figure out how "the core" does it.

Would it be possible to add something like a tickbox on the search screen to exclude anything with `Test` in the name or exclude the MFTF files?

Any thoughts?

**Comment by doninAtwix** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Hello, @cjnewbs!

Thank you for the great idea!
We'll try to find the way how to cover it in the plugin.
If you have any idea, please, share it.

Regards,

**Comment by doninAtwix** [comment]
One of the solutions. Open a search window, check the "File mask" and paste pattern: `!*test*`
For example:
<img width="852" alt="Screenshot 2022-01-14 at 13 35 37" src="https://user-images.githubusercontent.com/89141549/149512006-bca07bce-fbb6-407f-b6a5-6e178dc5c937.png">

Thank you.

**Comment by bohdan-harniuk** [comment]
Hello, @doninAtwix!

Thank you!
Please, continue your investigation!

Regards,

**Comment by doninAtwix** [comment]
Hello @bohdan-harniuk ,
We can create custom rule Scope for this but I don't know how to implement the pattern.

Thank you.

**Comment by bohdan-harniuk** [comment]
Hello, @cjnewbs!

I've implemented requested feature. It is done by introducing new search scope group named as **Magento** with search scope named as **All Files Except Tests**. It behaves as **All Places** search scope but it filters php test classes.

This feature will be delivered in the upcoming release: 4.2.2.

Regards,
