### ISSUE TITLE
Feature request: Enable Module helper menu in independent magneto2 modules.

### ISSUE THREAD

**Issue by tschallacka** [magento/magento2-phpstorm-plugin#621]
I have phpstorm set up with 3 projects in one display.

1) One project is the magento2 installation.
2) One project is my magento2 compatibility module for my target module
3) One project is a separate module that I wish to be able to use in magento2

in project `2` my json looks like this:
```json
{
  "name": "tschallacka/mage-storm",
  "description": "Adds the storm database library to magento for eloquent databases in magento 2",
  "minimum-stability": "stable",
  "version": "1.0.0",
  "license": "MIT",
  "type": "magento2-module",
  "psr-4": {
      "Tschallacka\\MageStorm": "src/Tschallacka/MageStorm"
  },
```

But the Magento helper menu doesn't appear.

![image](https://user-images.githubusercontent.com/8638425/130315311-81141cd5-9d1a-4bb1-a82d-8e07a7cf0590.png)

It does work for the magento2 installation

![image](https://user-images.githubusercontent.com/8638425/130315330-a268de02-d32f-4008-a1a8-facb9033f003.png)

The settings are enabled, and the path points to the magento2 installation.

![image](https://user-images.githubusercontent.com/8638425/130315359-d1c8bce9-a233-43cc-982e-59689bbcf7c0.png)

I've linked my other projects in the magento2 json via the "repositories" attribute.
```json 
   "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        {
            "type": "path",
            "url": "/home/tschallacka/Documents/github/mage-storm"
        },
        {
            "type": "path",
            "url": "/home/tschallacka/Documents/github/storm-database"
        }
    ], 
```

My feature request is that in projects where the main composer.json targets it as a magento2-module as type that in that directory the Magento generate Model etc... menu's appear.

---

I got a little working around working, by making a symlink in the app directory to my project, so I have access to the helper menus.

![image](https://user-images.githubusercontent.com/8638425/130315775-db0aaa6b-3e08-4f9c-b875-470a16d987d9.png)

But this is of course less than ideal to work with, it would just be better thatif the helper menu's would activate themselves if an independent project is tagged with type "magento2-module".

**Comment by bohdan-harniuk** [comment]
Hello, @tschallacka!

There is a native way to achieve this.
if it's still important to you, I can tell you how to do it.

Regards,

**Comment by tschallacka** [comment]
@bohdan-harniuk i'm interested, it would make life a bit easier.

**Comment by bohdan-harniuk** [comment]
Let's assume that we want to contribute to the separate module:

<img width="1462" alt="Screenshot 2022-02-01 at 23 20 05" src="https://user-images.githubusercontent.com/31848341/152053231-032d4bb8-0410-4a67-99a8-e6558269ed9a.png">

1. Open `Preferences... > PHP > Frameworks > Magento` and enable the Magento 2 integration and configure it as on the screenshot:

<img width="987" alt="Screenshot 2022-02-01 at 23 23 56" src="https://user-images.githubusercontent.com/31848341/152053769-5c53e11c-8e4a-4192-a955-482236e4e44a.png">

The **Magento installation path** here just to provide some required information for the integration. It is like a donor. 

2. Open `Preferences... > PHP` and let's get our "donor" to help us to connect all other PHPStorm useful features to our module development process:

<img width="987" alt="Screenshot 2022-02-01 at 23 27 29" src="https://user-images.githubusercontent.com/31848341/152054204-f9d92ade-972a-4c7e-baab-6accb53f4b99.png">

With **Include Path** is set to the root of our "donor"'s source code, we will be able to use such features as navigation to the Magento Framework and Magneto bundled extensions:

![Feb-01-2022 23-31-40](https://user-images.githubusercontent.com/31848341/152054850-36cceec6-fd44-42cd-b671-4d895323901a.gif)

Please, take a look at this instruction. 
@tschallacka, is it what you requested for?

Regards,

**Comment by tschallacka** [comment]
No, not at all. What I want that if I click on any folder I get the option to generate magdnto files, the creation menu only offers for folders that fit a certain format currently.

I want to be able to create a folder not in app/code, that has no module.xml and still generate the files you would find in a magento module.

**Comment by bohdan-harniuk** [comment]
@tschallacka, with the above configuration you can use all plugin features, but only with the valid module structure. 
It is the only one restriction, because it is technically required by implementation to have a valid Magento 2 module.

<img width="1111" alt="Screenshot 2022-02-02 at 08 42 25" src="https://user-images.githubusercontent.com/31848341/152106340-2e5d9ec0-564e-43b5-b27e-5eae50282a2c.png">

And it is useless to generate module files out of the module. 

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @tschallacka!

Any updates here?

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @tschallacka!

If I can help you here with something else, you can reopen this issue.
As I can see, we can close this issue for now.

Regards,
