### ISSUE TITLE
Action/Code Generation. Override view file in a custom theme

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#64]
User story:

* Right-click on a module view file (PHTML template, js file, HTML template, layout, etc)
* Select "Override in a theme"
* Dialog with the (app/design)theme's selection being shown
* After selecting a theme and click the Ok button the mentioned file is being copied to the appropriate directory of the theme, the file should contain proper copyrights

**Comment by sprankhub** [comment]
> Dialog with the (app/design)theme's selection being shown

It would be great if not only themes under `app/design` were supported, but also themes added via composer!

**Comment by VitaliyBoyko** [comment]
Hi @sprankhub 

I'm not sure whether it is a good idea to support editing files under the `vendor` directory. 
It would be better to edit them as a separate project as they have their own version controls system, deploy configuration, and so on. Then, add the main project to the `include paths` of the theme to have autocomplete and access to files.
So, right-clicking on files under `include paths` should be supported. 
Thanks for the suggestion!

**Comment by sprankhub** [comment]
I do understand your concerns. I also think that editing files in the vendor directory should not be supported. However, it is possible to use local directories as composer repositories:

- we put all custom modules and themes under a new directory
- this directory is configured as a local composer repository
- this directory is added to git
- themes inside this local directory are then included via composer require 

IMHO, the plugin should support such setups.

**Comment by VitaliyBoyko** [comment]
Thanks for the detailed explanation. 
I agree with that. 
If someone uses such a flow - it must be supported.

**Comment by sprankhub** [comment]
@VitaliyBoyko I just tried this with the latest version 2.0.1. Unfortunately, the "override in theme" action does not detect all themes, but only the ones under `app/design`. Please see my above comment why it makes sense to also support themes located at other places. Would you mind re-opening this or should I create a new issue? Thanks!

**Comment by VitaliyBoyko** [comment]
Will check. Ty
