### ISSUE TITLE
Action/Code Generation. ViewModel generation

### ISSUE THREAD

**Issue by roma-glushko** [magento/magento2-phpstorm-plugin#69]
It would be nice to facilitate best practices and add ViewModel generation for Magento modules.

References:
- https://www.yireo.com/blog/2017-08-12-viewmodels-in-magento-2
- https://devdocs.magento.com/guides/v2.3/extension-dev-guide/view-models.html

**Comment by lewisvoncken** [comment]
@roma-glushko maybe you can use http://mage2gen.com/ for the time being?

**Comment by roma-glushko** [comment]
@lewisvoncken absolutely, but this is a question of convenience. I believe, no one from the existing Magento code-gen tools can compete with code generation built-in IDE.

**Comment by vasilii-b** [comment]
I'll take care of it 😌

**Comment by VitaliyBoyko** [comment]
Hi @lewisvoncken 
Mage2gen library is great and powerful. All the Magento community appreciate your and contributors work.
We considered the Mage2gen usage but there are some concerns regarding this #46 
Therefore, unfortunately, we can't make this work :(
