### ISSUE TITLE
Add "module" prefix to module name in composer.json

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2-phpstorm-plugin#698]
**Is your feature request related to a problem? Please describe.**

According to [Magento Devdocs](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/composer-integration.html) each module should be named with a module prefix in the `composer.json`
Currently, each module is just named after the module name.
So, when I want to add `Vendor_TestModule`, it will be named `vendor/test-module`.

**Describe the solution you'd like** (*)

The correct name of the module should be: `vendor/module-test-module`  

**Describe alternatives you've considered**

**Additional context**

**Comment by artemii-karkusha** [comment]
@magento I am working on this

**Comment by artemii-karkusha** [comment]
@magento add to contributors team

**Comment by artemii-karkusha** [comment]
@magento I am working on this
