### ISSUE TITLE
[UCT:Inspection] Using non API class that is inheriting API interface

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#718]
### Description

The purpose of this inspection is to find places where there is used a class (not marked as API) that implements an interface marked as API.

**For example:**

The client has Magento V1 and wants to upgrade it to the V2 (versions are abstract to describe the idea). In Some class there is used a TestClass. It is not marked as API, but it implements an Interface marked as an API. That inspection should highlight using of this class and describe the issue.

**The UML diagram of the example case:**

![using-non-api-class-that-has-api-interface](https://user-images.githubusercontent.com/31848341/140070534-0473be59-61db-415e-af42-f708ed89232a.jpg)

```php
/**
 * @api
 */
interface TestInterface {
    public function methodA();
}

class TestClass implements TestInterface
{
    public function methodA(){}
    public function methodB(){}
}

class SomeClass
{
    public function __construct(
        TestClass $object // Possible dependency on implementation details. 
    ) {
        $object->methodB(); // OK
    }
}
```

**Severity level:** ERROR

### Key points for implementation

- all PHP inspections should be grouped under the `com.magento.idea.magento2uct.inspections` package.
- all PHP inspections must be inherited from the com.jetbrains.php.lang.inspections.PhpInspection
- all inspections should have checking if it should be run with the current tool configurations
- all inspections should cover cases for running from the UCT tool run option and from the PHPStorm itself
- if covered area is not already supported it should be checked and added to the `com.magento.idea.magento2uct.inspections.UctInspectionManager`
- each new inspection must be registered in PHPStorm way in the plugin.xml file
- each new inspection must be described in the appropriate html file: `resources/inspectionDescriptions/FileName.html` (to be available in the inspections enable/disable menu)
- each new inspection must be registered for running from the UCT tool run option in the `com.magento.idea.magento2uct.packages.SupportedIssue`

Approximate time to develop: 4h

**Comment by Iamwade** [comment]
@magento I am working on this
