### ISSUE TITLE
[UCT:Inspection] Inherited from non API interface

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#719]
### Description

The purpose of this inspection is to find places where there is extended a class not marked as API.

**For example:**

The client has Magento V1 and wants to upgrade it to the V2 (versions are abstract to describe the idea). There is a Some interface extends a TestInterface. The TestInterface is not marked as API. That inspection should highlight extending from this interface and describe the issue.

**The UML diagram of the example case:**

![inherited-not-api-interface](https://user-images.githubusercontent.com/31848341/140073197-46cafe61-b3b9-487d-9b2f-44b5062d5073.jpg)

**Severity level:** ERROR

### Key points for implementation

- all PHP inspections should be grouped under the `com.magento.idea.magento2uct.inspections` package.
- all PHP inspections must be inherited from the com.jetbrains.php.lang.inspections.PhpInspection
- all inspections should have checking if it should be run with the current tool configurations
- all inspections should cover cases for running from the UCT tool run option and from the PHPStorm itself
- if covered area is not already supported it should be checked and added to the `com.magento.idea.magento2uct.inspections.UctInspectionManager`
- each new inspection must be registered in PHPStorm way in the plugin.xml file
- each new inspection must be described in the appropriate html file: `resources/inspectionDescriptions/FileName.html` (to be available in the inspections enable/disable menu)
- each new inspection must be registered for running from the UCT tool run option in the `com.magento.idea.magento2uct.packages.SupportedIssue`

Approximate time to develop: 4h

**Comment by Iamwade** [comment]
@magento I am working on this
