### ISSUE TITLE
Generate PHP (X)debug Step Filter configuration

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2-phpstorm-plugin#736]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when stepping through an Xdebug session in Magento 2 because I encounter tons of interceptor or proxy files due to the Plugin system. PhpStorm offers a way to skip file paths when stepping through a debugger session, which can be configured under Settings > PHP > Debug > Step Filter > Skipped Paths.

**Describe the solution you'd like** (*)

It would be great to have a button in the Magento 2 PhpStorm plugin (just like the Regenerate URN button) to generate this configuration.

**Describe alternatives you've considered**

I created a hacky magerun2 addon to generate this configuration and append it to the `.idea/php.xml` file, see this tweet; https://twitter.com/PeterJaap/status/1456621266782281735

**Additional context**

I've already done some preliminary work, such as adding the button itself;

![image](https://user-images.githubusercontent.com/431360/140601297-fc45a697-4df5-4f7e-b4dd-65da745e2c15.png)

But my limited Java knowledge is preventing me from finishing this myself without investing tons of hours. While I'm sure any of the devs here can easily complete this functionality in considerably less time.

See my unfinished PR here; https://github.com/magento/magento2-phpstorm-plugin/pull/737

**Comment by doninAtwix** [comment]
@magento I am working on this

**Comment by doninAtwix** [comment]
Hello @bohdan-harniuk.
I have tried to reproduce expected behaviour on my machine, but no luck so far.
Thank you

**Comment by bohdan-harniuk** [comment]
Hello, @doninAtwix!

Thanks for trying!

Regards,

**Comment by bohdan-harniuk** [comment]
@peterjaap, any updates here?

We cannot gain expected results (manually) without your help.

Regards,

**Comment by bohdan-harniuk** [comment]
On hold. Not reproducible, no response.

Can be reopened only with the reporter assistance.

**Comment by peterjaap** [comment]
@bohdan-harniuk I just had time to look at it again, you are correct; it doesn't work. I could've sworn it did work when I worked on it in November... feels like a PhpStorm bug.
