### ISSUE TITLE
Add the ability to open all plugins in the Find Tool Window

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2-phpstorm-plugin#833]
**Is your feature request related to a problem? Please describe.**

When you click the plugin icon in the gutter, we are shown a list of all plugins from which we can choose any plugin, but this is not convenient when we need to analyze all/many plugins. To do this, you have to constantly return to the main class and click on the icon again and select the plugin class. But if there are 10 or more such plugins, it is very easy to get confused in them and it is very routine and annoying. 

![image](https://user-images.githubusercontent.com/1055999/145212494-8b837740-efcf-4903-ab1d-634451e48c2c.png)

**Describe the solution you'd like**

To improve the interaction with this element, you need to add a header in which we can open all related plugins in the Find Tool Window, as is done for overridden/overrides methods.

![image](https://user-images.githubusercontent.com/1055999/145212544-0a4ac9ab-df27-4133-99be-a2df5fcbd328.png)

![image](https://user-images.githubusercontent.com/1055999/145212556-b89100ac-bb69-4eef-8fbd-8a77844a32af.png)

![image](https://user-images.githubusercontent.com/1055999/145212586-e451e1aa-1230-4d5d-a18a-cc277a37d238.png)

**Additional context**

Perhaps there are other places where this solution can be applied, but I have not yet met them or do not remember.

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs!

Thank you for your proposal! It is great!
We'll try to include it in the next release.

Thanks, Bohdan

**Comment by artemii-karkusha** [comment]
@magento I am working on this

**Comment by Iamwade** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Hello, @DmitryFurs!

We've finished development here.
This update will be delivered in the upcoming release: 4.2.2.
Thank you again for the great idea!

Regards,
