### ISSUE TITLE
Module name declaration inspection flags valid code

### ISSUE THREAD

**Issue by lfolco** [magento/magento2-phpstorm-plugin#834]
**Describe the bug** (*) 

Adding a `ExpressionConverter` translation to `registration.php` causes the invalid module name inspection to fire. When using long table names, you can add a translation to the `registration.php` file in order to have foreign key names that are more descriptive, instead of the ones that it generates like `FK_1398WO8U4OR8UEO48ROE4OTJO3`. This translation gets flagged as an error.

**To Reproduce** (*) 

1. Open up any registration.php file
2. Add the following line: `\Magento\Framework\DB\ExpressionConverter::addTranslate('subscriber_queue', 'subqueue');`
3. See error "Provided module name does not match expected"

**Please complete the following information:** (*) 

 - OS: MacOS
 - PhpStorm/Intellij version: 2021.1.4
 - Plugin Version: 4.0.0

**Comment by bohdan-harniuk** [comment]
Hello, @lfolco!

Could you please share code block for better understanding?

Thanks, Bohdan

**Comment by lfolco** [comment]
```
use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Aescripts_NotifyVersion', __DIR__);

// Generated FK names were too long, need to shorten a few things
\Magento\Framework\DB\ExpressionConverter::addTranslate('email_tracking', 'trck');
\Magento\Framework\DB\ExpressionConverter::addTranslate('notify_version', 'notifyver');
```

![image](https://user-images.githubusercontent.com/1709329/147286587-fdf4aa3b-f6bf-47cf-9461-424887b838bb.png)

**Comment by bohdan-harniuk** [comment]
Hello, @lfolco!

Thank you for your help.
I'he reproduced this bug:

<img width="1211" alt="Screenshot 2021-12-24 at 09 51 39" src="https://user-images.githubusercontent.com/31848341/147331424-ac957af0-03f3-4e41-b7c4-4b589a639344.png">

**Comment by bohdan-harniuk** [comment]
Hello, @lfolco!

I've fixed this bug. 
Fix will be delivered in the upcoming release: 4.2.2

Regards,

**Comment by lfolco** [comment]
Thank you!
