### ISSUE TITLE
[Bug] Message Queue Connection does not match Naming Conventions

### ISSUE THREAD

**Issue by msyhr** [magento/magento2-phpstorm-plugin#837]
If a user follows the documentation here: https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html#start-message-queue-consumers to do the initial setup Rabbit MQ they instruct the user to use **amqp** as the connection name.

If that user then uses the PHP Storm plugin to scaffold a new message queue, this extension defines that connection name as **ampq** (p and q swapped). 

This will cause the CLI and most likely other executions to fail. 

![queue](https://user-images.githubusercontent.com/22968596/145457153-dbacef9e-867b-4097-87a8-50f698e17bae.png)

This can be easily resolved by altering the connection names in either the generated .xml files or in your env.php, and I know (I think?) that the connection name is just an arbitrary string, but some others might run into the same issue I did and not realize it.

**Comment by bohdan-harniuk** [comment]
Hello, @msyhr !

Thank you for your report!
We'll try to include fix in the upcoming release.

Thanks, Bohdan!

**Comment by bohdan-harniuk** [comment]
This issue successfully reproduced: 

<img width="1007" alt="Screenshot 2021-12-16 at 17 16 58" src="https://user-images.githubusercontent.com/31848341/146398216-e8764039-b6ed-4b94-b347-55f3a0efa332.png">

**Comment by bohdan-harniuk** [comment]
Hello, @msyhr!

This issue is fixed and will be delivered in the upcoming release: 4.2.2.

Thank you for your report!
