### ISSUE TITLE
[Bug] Observer creation action is no longer visible

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#853]
**Describe the bug** (*) 

Long time ago was introduced an action for creating new observer on any event in the codebase. Now this action is no longer visible.

**To Reproduce** (*) 

1. Go to any declared event
2. Open context menu under the event name
3. See absent "Create a Magento Observer" action

**Expected behavior** (*) 

The "Create a Magento Observer" action is available in the context menu when clicking on the declared event name.
[Wiki.](https://github.com/magento/magento2-phpstorm-plugin/wiki/1.0.0-Release#create-an-observer-for-an-event)

A new observer is successfully generated with all required files.

**Screenshots**

<img width="782" alt="Screenshot 2021-12-16 at 15 06 36" src="https://user-images.githubusercontent.com/31848341/146377400-8120b001-bf64-48d8-854a-6364726b6a0d.png">

**Please complete the following information:** (*) 

 - OS: no metter
 - PhpStorm/Intellij version: 2021.2
 - Plugin Version: 4.2.0|4.2.1 (maybe earlier versions)

**Additional context**

**Mainline branch is:** _4.2.2-develop_

**Comment by artemii-karkusha** [comment]
@magento I am working on this
