### ISSUE TITLE
Wrong namespace when generation a new controller

### ISSUE THREAD

**Issue by nenes25** [magento/magento2-phpstorm-plugin#855]
**Describe the bug** (*) 

When generating a controller the namespace is wrong, and the controller does not works.

**To Reproduce** (*) 

1. I create a module "Learn_ControllerIssue" in app/code
2. Right click on the directory "ControllerIssue" then "New / Module File / Magento2 Controller"
3. I fill the popin with the following data
![image](https://user-images.githubusercontent.com/7163132/146508785-63f97900-a103-4f0c-bb1d-b4fbe5a9d7c0.png)
4. The generated namespace is Learn\ControllerIssue\ControllerDemo 
![image](https://user-images.githubusercontent.com/7163132/146508848-d89f8b9d-83d5-4e05-a159-89bbf44a0d33.png)
5. The controller does not works

**Expected behavior** (*) 

The generated namespace should be Learn\ControllerIssue\Controller\Demo 
The separation between the parent directory and the controller name is missing

**Screenshots**

**Please complete the following information:** (*) 

 - OS: Ubuntu Linux 18.04
 - PhpStorm/Intellij version: 2021.3
 - Plugin Version: 4.2.1

**Additional context**

**Comment by bohdan-harniuk** [comment]
Hello, @nenes25!
Thank you for your report!

This issue was fixed in the #844!
We will deliver this fix in the upcoming release: 4.2.2.

Thank you, Bohdan
