### ISSUE TITLE
Code generation. di.xml plugin template description

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#88]
### Description (*)
Describe the purpose of the di.xml plugin code template and containing variables. (Editor > File and Code templates)

See the example here #50

![image](https://user-images.githubusercontent.com/20116393/78268470-e4656c00-7510-11ea-98ee-325fba9cbcbc.png)

**Comment by vasilii-b** [comment]
Hi @VitaliyBoyko,
May I have a look at this one? Thanks!
