### ISSUE TITLE
Eliminate LineMarkerXmlTagDecorator#checkAdd usage

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#899]
**Is your feature request related to a problem? Please describe.**

The com.intellij.psi.PsiElement#checkAdd method is deprecated. It is used in the: `com.magento.idea.magento2plugin.linemarker.xml.LineMarkerXmlTagDecorator#checkAdd`.

**Describe the solution you'd like** (*)

Eliminate usage of deprecated method.

**Comment by artemii-karkusha** [comment]
@magento I am working on this
