### ISSUE TITLE
getting Error Incompatible Error on  install PHPStorm  8.0.1

### ISSUE THREAD

**Issue by devamitbera** [magento/magento2-phpstorm-plugin#9]
Downloaded Magento2 pLugin  from https://plugins.jetbrains.com/plugin/8024-magento-phpstorm

And Downloaded  0.2.3 version and trying to install  `magento2plugin.jar` using  **Install Plugin from disk**

And getting Error Incompatible Error
![php](https://user-images.githubusercontent.com/6008488/35430931-7576d44e-02a0-11e8-9cf4-fa5957df0ad4.png)

**Comment by voleye** [comment]
@devamitbera , you probably should update the version of your PhpStorm
