### ISSUE TITLE
Eliminate com.google.gson.JsonParser#parse usage

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#913]
**Is your feature request related to a problem? Please describe.**

The com.google.gson.JsonParser#parse method is deprecated. It is used in the: `com.magento.idea.magento2plugin.actions.generation.generator.ModuleComposerJsonGenerator#getDependencyData`.

**Describe the solution you'd like** (*)

Eliminate usage of deprecated method.

**Comment by Iamwade** [comment]
@magento I am working on this
