### ISSUE TITLE
Add how to create SandBox for development info into the README.md

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#914]
**Is your feature request related to a problem? Please describe.**

Add to the README.md information about "How to create SandBox for development".

**Describe the solution you'd like** (*)

Would be great to add this information into the **Setting up development environment** section.

**Mainline branch is:** 4.3.0-develop

**Comment by doninAtwix** [comment]
@magento I am working on this
