### ISSUE TITLE
Generate compatibility inspections index for the latest 2.4.4 beta

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2-phpstorm-plugin#920]
UCT inspections index should be generated for the latest 2.4.4-beta4 version
2.4.4-beta1 and 2.4.4-beta2 version indexes can be removed as non-actual.

**Comment by bohdan-harniuk** [comment]
Hello, @sivaschenko!

I've added support of the Magento 2.4.4-beta4.
Awaiting for new issues to improve the UCT in the plugin.

Regards,
