### ISSUE TITLE
Package name showing on windows

### ISSUE THREAD

**Issue by hryvinskyi** [magento/magento2-phpstorm-plugin#929]
**Describe the bug** (*) 

When creating a module in the package directory showed "Package Name" input https://i.imgur.com/XyGBfTe.png
and when click "OK" module create in incorect path: https://i.imgur.com/Q03fpqU.png
plugin works on Linux

**To Reproduce** (*) 

1. Go to '/app/code/PackageVendorDir'
2. Click right button on mouse -> New -> Magento 2 Module
3. Fill All fields

**Please complete the following information:** (*) 

 - OS: Windows 11
 - PhpStorm/Intellij version: 2022.3.1
 - Plugin Version: 4.2.1

**Comment by Iamwade** [comment]
@hryvinskyi Hi!
Thanks for the bug report. I tried to reproduce on Mac OS but everything works fine for me. As far as I understand, everything works well on Linux too.
Please clarify, were you able to reproduce this error only on Windows?

Thank you.

**Comment by bohdan-harniuk** [comment]
Hello, @hryvinskyi!

Please, check comment from @Iamwade.
I could not reproduce this bug as well:

<img width="1071" alt="Screenshot 2022-01-23 at 14 23 14" src="https://user-images.githubusercontent.com/31848341/150678261-941ca276-4319-40d6-83a0-69d8ba20eade.png">

Regards,

**Comment by hryvinskyi** [comment]
@hryvinskyi Hi!
Yes, this bug i can reproduce only on wondows 10 / windows 11 ![2022-01-25_20-34-32](https://user-images.githubusercontent.com/9294098/151038119-d06bd32a-f0b8-4c72-9956-a6bbe9eceb9c.gif)
On Linux it works fine for me

**Comment by bohdan-harniuk** [comment]
Hi, @hryvinskyi!

Thank you for your response!
We will try to solve this issue.

Regards,

**Comment by doninAtwix** [comment]
Hi @bohdan-harniuk .
This issue has been reproduced on the windows/macOs/linux operation systems.

<img width="885" alt="Screenshot 2022-02-18 at 16 44 57" src="https://user-images.githubusercontent.com/89141549/154705585-515241b4-864e-4118-97d4-8df65351554e.png">

Thank you.

**Comment by bohdan-harniuk** [comment]
Hello, @doninAtwix!

Thank you for your work here!
Please, fix this issue.

Hello, @hryvinskyi!
We will fix this issue and include it into the upcoming release.

Regards,

**Comment by hryvinskyi** [comment]
@bohdan-harniuk @doninAtwix thanks for news
