### ISSUE TITLE
Extend uiComponent highlighting with is integration enabled check

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#941]
**Is your feature request related to a problem? Please describe.**

We need to extend feature developed in the #276. We should add additional check if the Magento 2 integration is enabled. 

**Describe the solution you'd like** (*)

We should highlight `<script type="x-magento-init">` as JSON **only if** the Magento 2 integration is enabled.

**Additional context**

Mainline branch: **4.3.0-develop**

**Comment by doninAtwix** [comment]
@magento I am working on this
