### ISSUE TITLE
Extend custom search scope (to exclude test files from search) with is integration enabled check

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#943]
**Is your feature request related to a problem? Please describe.**

We need to extend feature developed in the #935. We should add additional check if the Magento 2 integration is enabled. 

**Describe the solution you'd like** (*)

We should show the Magento scopes only if the Magento 2 integration is enabled.

**Additional context**

**Scope provider implementation:** `com.magento.idea.magento2plugin.lang.psi.search.MagentoSearchScopesProvider`.

Mainline branch: **4.3.0-develop**

**Comment by doninAtwix** [comment]
@magento I am working on this
