### ISSUE TITLE
Add missing title to "Module File" form

### ISSUE THREAD

**Issue by Iamwade** [magento/magento2-phpstorm-plugin#955]
**Describe the bug** (*) 

We have missing titles for some forms:
- Magento 2 Email Template
![image](https://user-images.githubusercontent.com/33068778/152367674-be1587a4-4392-458c-bd34-ffabea1374d1.png)
- Magento 2 Models
![image](https://user-images.githubusercontent.com/33068778/152367592-c410807b-4ec1-4ec3-8c6a-255413ce01b0.png)

**To Reproduce** (*) 
- Right click on the module
- New -> Model File
![image](https://user-images.githubusercontent.com/33068778/152368154-97dd28cd-05a1-474d-96f9-a5540b79315e.png)

**Expected behavior** (*) 

Add title:
- Create a new Magento 2 Email Template
- Create a new Magento 2 Models

**Comment by SilinMykola** [comment]
@magento I am working on this
