### ISSUE TITLE
New Magento 2 Entity. Moving Example to the placeholder.

### ISSUE THREAD

**Issue by Iamwade** [magento/magento2-phpstorm-plugin#959]
Patch 4.3.0 adds the ability to add placeholders to the input field.
https://github.com/magento/magento2-phpstorm-plugin/pull/938

We need to move the tooltips to the text input field.
![image](https://user-images.githubusercontent.com/33068778/152701807-3dab9567-2312-4bf2-b923-b1fd50f211aa.png)

**Comment by Iamwade** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Related to the #598

**Comment by Iamwade** [comment]
Hi @bohdan-harniuk 
Tooltips have been moved to a placeholder throughout the dialog
![image](https://user-images.githubusercontent.com/33068778/154562647-59f9b6c0-b59a-488c-909b-5a900e1a6e3e.png)
![image](https://user-images.githubusercontent.com/33068778/154562699-160f1822-0e4c-4e22-8cef-59245ed7c7da.png)
![image](https://user-images.githubusercontent.com/33068778/154562727-5ca59da0-3997-4dbc-a160-0a73fa6555a2.png)
![image](https://user-images.githubusercontent.com/33068778/154562741-69dac71b-a009-4b5c-aa50-ac3e0c5ac007.png)
You can start code review.
Thank you.
