### ISSUE TITLE
New Magento2 Controller. Add a placeholder.

### ISSUE THREAD

**Issue by Iamwade** [magento/magento2-phpstorm-plugin#960]
Patch 4.3.0 adds the ability to add placeholders to the input field.
https://github.com/magento/magento2-phpstorm-plugin/pull/938

We need to add placeholders to the creation of a new controller.
![image](https://user-images.githubusercontent.com/33068778/152702004-4b6961e6-e745-472e-8924-4b466ab85997.png)

Action Name: Directory name
Controller Name: Class name

@bohdan-harniuk Are you agree with these placeholders?

**Comment by Iamwade** [comment]
@magento I am working on this

**Comment by bohdan-harniuk** [comment]
Related to the https://github.com/magento/magento2-phpstorm-plugin/issues/598

**Comment by SilinMykola** [comment]
@magento I am working on this
