### ISSUE TITLE
Add a new context dependent Action for the di.xml file generation

### ISSUE THREAD

**Issue by bohdan-harniuk** [magento/magento2-phpstorm-plugin#961]
**Is your feature request related to a problem? Please describe.**

We should add di.xml file generation to the context actions, so that we can generate a di.xml file wherever it can be generated depending on the clicked file or directory.

The original idea came from the #861.

**Describe the solution you'd like** (*)

We have developed a new context dependent actions group in the #958.

To add new file generation action that depends on context:

1. create an action class that extends `com.magento.idea.magento2plugin.actions.context.AbstractContextAction`
2. register it in the plugin.xml file inside the **MagentoContextBasedActionsGroup** group
3. implement the **isVisible** method to define condition where to show this action
4. implement the **getProperties** method to specify properties that should be auto-populated from the known context (leave empty for user-defined values)

**Describe alternatives you've considered**

**Additional context**

Mainline branch: 4.3.0-develop

**Comment by SilinMykola** [comment]
@magento I am working on this
