### ISSUE TITLE
[UCT] Error is not displayed if the generated class of the method called exists

### ISSUE THREAD

**Issue by eliseacornejo** [magento/magento2-phpstorm-plugin#984]
**Describe the bug** (*) 

No error is displayed when calling a method of a class that was generated when compiling the code.

**To Reproduce** (*) 

1. Install a Magento project. In my case 2.4.2 version
2. Compile it: bin/magento setup:di:compile
3. Create some customised code like this for example:

```
public function match(\Magento\Framework\App\RequestInterface $request) {
        $info = $request->getPathInfo();
}
```
4. Execute the phpstorm plugin. I tried 4.2.3 and 4.2.2
5. Right now no error is displayed for the call of the method getPathInfo() ** as when the code was compiled, a proxy class was generated, with the method. But in this case, this is error should be displayed:

`* [ERROR][1429] Line 33: Called method '\Magento\Framework\HTTP\PhpEnvironment\Request.getPathInfo' is not marked as an API`

**Expected behavior** (*) 
This is error should be displayed:

`* [ERROR][1429] Line 33: Called method '\Magento\Framework\HTTP\PhpEnvironment\Request.getPathInfo' is not marked as an API`

**Please complete the following information:** (*) 

 - OS: MacOs
 - PhpStorm/Intellij version: 2021.2.4
 - Plugin Version: 4.2.3 and 4.2.2

**Comment by bohdan-harniuk** [comment]
Hello, @eliseacornejo!

I've successfully reproduced this bug.

**Before running dependencies compilation:**

<img width="1075" alt="Screenshot 2022-03-19 at 13 45 28" src="https://user-images.githubusercontent.com/31848341/159119904-6a87769e-651b-4c98-a8ff-15e6606125f0.png">
<img width="996" alt="Screenshot 2022-03-19 at 13 44 52" src="https://user-images.githubusercontent.com/31848341/159119905-d8ca30df-ede6-4126-9912-3ff7de65c63e.png">

**After:**

<img width="723" alt="Screenshot 2022-03-19 at 13 49 05" src="https://user-images.githubusercontent.com/31848341/159119910-bca3abf6-5b9c-4076-9ba8-64913ff4c7bf.png">

Thank you, for a such detailed description of the bug.

Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @eliseacornejo!

This issue is fixed and it will be delivered in the upcoming release: 4.3.0.

Regards,
